### ISSUE TITLE
Add support for ES6 classes that extend React.Component

### ISSUE THREAD

**Issue by fkling** [reactjs/react-docgen#10]
For example

```js
class Foo extends React.Component { }

Foo.propTypes = { ... };
```

**Comment by pvolok** [comment]
Babel also supports this:

```js
class Foo extends React.Component {
  static propTypes = { ... }
}
```

**Comment by fkling** [comment]
I will take take care of this after I'm back from vacation. My current plan is to change the structure of he value that is passed from the resolvers to the handlers, which will make it easier to add this feature.

**Comment by theogravity** [comment]
+1

**Comment by jherr** [comment]
+1

**Comment by silentrob** [comment]
+1

**Comment by fkling** [comment]
As a heads up, I'm planning to have this ready until the end of this week!

**Comment by jherr** [comment]
Is there an option for +10,000? ;-) Thanks Felix!

**Comment by fkling** [comment]
@jherr: :) I actually answered your email, but it seems it couldn't be delivered due to security checks. It contained the same info though ;)

**Comment by jherr** [comment]
Weird, though sadly not surprising.

**Comment by fkling** [comment]
I pushed all changes to master. I will run one more test tomorrow and release a new version if everything goes well.

**Comment by theogravity** [comment]
You are the man! :D

**Comment by fkling** [comment]
Alright, published as [v2.0](https://github.com/reactjs/react-docgen/tree/v2.0.0), since it potentially breaks custom handlers (if someone does that). Please try it and let me know about any issues!

**Comment by theogravity** [comment]
Yay, thank you! Will try over the weekend

**Comment by jherr** [comment]
Works great! Thanks!

**Comment by theogravity** [comment]
Confirmed working! Thank you!
