### ISSUE TITLE
Doesn't detect stateless functional components that return ternary expressions

### ISSUE THREAD

**Issue by 0xR** [reactjs/react-docgen#107]
Given a component defined like this:

``` javascript
import React from 'react';

export default function Button(props) {
  const button = <input type="button" />;
  return props.next ? <div id="next">{button}</div> : button;
}

Button.propTypes = {
  next: React.PropTypes.bool,
};
```

I get this error: `Error: No suitable component definition found.`

A workaround for this is not to use a ternary:

``` javascript
import React from 'react';

export default function Button(props) {
  const button = <input type="button" />;
  if (props.next) {
    return <div id="next">{button}</div>;
  }
  return button;
}

Button.propTypes = {
  next: React.PropTypes.bool,
};
```

This gives me the correct output:

``` json
{
  "description": "",
  "methods": [],
  "props": {
    "next": {
      "type": {
        "name": "bool"
      },
      "required": false,
      "description": ""
    }
  }
}
```

Supporting ternary statements would be nice since I have a lot of them in my codebase.

**Comment by dptoot** [comment]
+1  
This is also applicable to the the ternary short hand 

```javascript
export default function Button(props) {
  const button = <input type="button" />;
  return props.show && (
    <div id="next">{button}</div>
  );
}
```

**Comment by fkling** [comment]
Yep, that should definitely work.

**Comment by dptoot** [comment]
Don't want to lump on more grief but just informing if it may assist in debugging...

I am also seeing the issue if the return value is a React API method

```javascript
function Popup({url, width, height, children, ...rest}) {

    const handleOnClick = () => {
        window.open(url, 'popup', `height=${height},width=${width},scrollbars=yes`, false);
    };

    return (
        React.cloneElement(children, {
            onClick: createChainedFunction(handleOnClick, children.props.onClick)
        })
    );
}

```

**Comment by fkling** [comment]
Thanks @dptoot! Yeah, we "just" have update the heuristic to account for these cases. https://github.com/reactjs/react-docgen/blob/master/src/utils/isStatelessComponent.js is the file if anyone wants to take a stab at it.

**Comment by khankuan** [comment]
@fkling Proposing that we use `propTypes` to guess since a function can literally do anything such as calling an imported module. But in most cases `propTypes` should be defined (or worst case we can define an empty object). Thoughts?

**Comment by fkling** [comment]
@khankuan: Seems reasonable to me. I'd still keep the current heuristic and fall back to that if the `propTypes` check comes back negative.

**Comment by khankuan** [comment]
@fkling i intend to add detection via propTypes and defaultProps but couldn't figure what's the best way to traverse the given path and grab it's object properties to inspect. Could you give a little hint on any examples that are similar? Thanks :)

**Comment by mike-robertson** [comment]
Does this issue still need a fix? I still see issues if I do a ternary or `bool && <div />`.

**Comment by danez** [comment]
@mike-robertson Yes, nothing happened here since it was opened. We are all a little bit short on time. If you want feel free to open a PR.

**Comment by pke** [comment]
It seems the eslint react plugin does a pretty good job on detecting stateless components. Maybe we should see how they do it? Because it does not complain about this perfectly valid stateless component described in #232

**Comment by caseycallow** [comment]
Ran into this earlier. Converting to an if statement fixes it temporarily. Would really like to be able to use ternary statements with SFCs though.

Works:
```
const Heading = ({ element: Element, children }) => {

  const heroMarkup = <h1>{children}</h1>;
  const headingMarkup = <Element>{children}</Element>;
  
  if (Element === "hero") return heroMarkup;
  return headingMarkup;
};
```
Doesn't work but should:
```
const Heading = ({ element: Element, children }) => {

  const heroMarkup = <h1>{children}</h1>;
  const headingMarkup = <Element>{children}</Element>;
  
  return Element === "hero" ? heroMarkup : headingMarkup;
};

**Comment by bregenspan** [comment]
This appears to have been fixed in https://github.com/reactjs/react-docgen/commit/d2c096f2e4212606fe6f283f740ab0d74e77c103 - @caseycallow @0xR can you confirm?
