### ISSUE TITLE
Are cli options working?

### ISSUE THREAD

**Issue by awesomejerry** [reactjs/react-docgen#126]
I'm using react-docgen by cli. However, `--ignore`, `--exclude` and `--resolver` seem not working at all. It keeps parsing those unwanted files and output `No suitable component definition found`, which is really annoying since they're not meant to be generated docs.

**Comment by fkling** [comment]
The tests are passing, so I'd say yes. Can you provide more details to reproduce the issue?

**Comment by awesomejerry** [comment]
I initialized a new and simple project:
```
{
  "name": "react-docgen-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "docgen": "react-docgen src --pretty",
    "docgen-resolver": "react-docgen src --pretty --resolver findExportedComponentDefinition",
    "docgen-ignore": "react-docgen src --pretty --ignore [styles]",
    "docgen-exclude": "react-docgen src --pretty --exclude ['/^(style)/g']"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "react-docgen": "^2.10.0"
  }
}
```

with following files:
<img width="217" alt="2016-09-28 11 02 25" src="https://cloud.githubusercontent.com/assets/6601073/18899368/1a4ab86e-856b-11e6-92da-6f4c0578ac5e.png">

and those files are simple:
Component.js:
```
import React, { Component } from 'react';

  /**
   * This is a simple component
   */
class MyComponent extends Component {
  render() {
    return (
      <div>123</div>
    );
  }
}

export default MyComponent;
```

style.js:
```
export default {
  title: 'This shouldn\'t be parsed by react-docgen',
};
```

No matter which script I run, the error is the same:
<img width="1006" alt="2016-09-28 11 04 44" src="https://cloud.githubusercontent.com/assets/6601073/18899418/70ff9300-856b-11e6-8686-cb24f36b3f94.png">

I thought the default behavior is that react-docgen only parse react component files. However the cli options seem not working either.

**Comment by n1313** [comment]
I have spent a couple of hours trying to exclude some files and after digging into sources of `node-dir` (see [1](https://github.com/fshost/node-dir/blob/e12df4e43d83c4ad0eba6f14a66512ef28dec2f5/lib/readfiles.js#L28), [2](https://github.com/fshost/node-dir/blob/e12df4e43d83c4ad0eba6f14a66512ef28dec2f5/lib/readfiles.js#L97)) managed to do it. So it seems that CLI options are working. The docs could be improved though.

This command will recursively consume `src`, exclude every file named `index.js` and output the result into a file:
    `react-docgen src --pretty -e index.js -o output.json`

**Comment by fkling** [comment]
@n1313: Specifying `-e` multiple times should work:

```sh
react-docgen src --pretty -e foo.js -e bar.js -o output.json
```

@awesomejerry: You partly using the API incorrectly (I think) and it's partly an issue with react-docgen. To ignore directories you should do

```sh
react-docgen src --pretty --ignore styles
```

i.e. omit the brackets.

Providing regular expressions as patterns for `--exclude` doesn't seem to currently work since we are not converting the provided parameters to regular expressions. I'd appreciate it if you open PR to fix it.

**Comment by awesomejerry** [comment]
The `-e style.js` part works, but it's very trivial to exclude every kind of files. The better way is what it's already listed in README `this will look for the exported component created through React.createClass or a class definition in the provided source`. Only parse files that define components.
I'm not sure if it's currently working or should I put some configs in the command.

**Comment by fkling** [comment]
> Only parse files that define components.

Well, we have to parse the file in order to know whether it defines components or not. However, maybe we should create a friendlier output that simply lists in which files it didn't find component definitions (and provide a CLI option to suppress that information).

**Comment by Kryten0807** [comment]
The documentation for the exclude option says "Filename pattern to exclude" - I'm reading that to mean that it will match a pattern and exclude those files. But I can't find a way to specify a pattern that works.

I can explicitly exclude files by specifying the full file name, but cannot exclude files by pattern. For example, I'm trying:

    react-docgen src/components/ -o test.json -e *.spec.js

And getting a whole bunch of "No suitable component definition found" errors.

I've tried a number of different ways of specifying that pattern:

    # try * wildcards?
    react-docgen src/components/ -o test.json -e *.spec.js
    react-docgen src/components/ -o test.json -e **/*.spec.js
    react-docgen src/components/ -o test.json -e src/components/*.spec.js
    react-docgen src/components/ -o test.json -e src/components/**/*.spec.js

    # maybe a regex?
    react-docgen src/components/ -o test.json -e '/.*.spec.js/'
    react-docgen src/components/ -o test.json -e '.*.spec.js'
    react-docgen src/components/ -o test.json -e .*.spec.js

**Comment by DanielRuf** [comment]
Same here, it does not see to work with the excludes.

**Comment by DanielRuf** [comment]
Same here, it does not seem to work with the excludes.
