### ISSUE TITLE
Nested union type in react-native docs

### ISSUE THREAD

**Issue by brentvatne** [reactjs/react-docgen#13]
In [ViewStyleProps](https://github.com/facebook/react-native/blob/master/Libraries/Components/View/ViewStylePropTypes.js) I would like to change `transform` to the following:

```javascript
  transform: ReactPropTypes.arrayOf(
    ReactPropTypes.oneOfType([
      ReactPropTypes.shape({rotation: ReactPropTypes.number}),
      ReactPropTypes.shape({scaleX: ReactPropTypes.number}),
      ReactPropTypes.shape({scaleY: ReactPropTypes.number}),
      ReactPropTypes.shape({translateX: ReactPropTypes.number}),
      ReactPropTypes.shape({translateY: ReactPropTypes.number})
    ])
  ),
```

The current output from docgen is this:

![screen shot 2015-05-06 at 10 24 12 am](https://cloud.githubusercontent.com/assets/90494/7499062/1f9cc89e-f3da-11e4-8fd7-11ae91eafd1a.png)

I would prefer for it to be this:

![screen shot 2015-05-06 at 10 25 50 am](https://cloud.githubusercontent.com/assets/90494/7499098/4a2d5416-f3da-11e4-95b5-a0fcf991efb0.png)

@fkling - am I doing something incorrectly here? If a patch is necessary, could you point me in the right direction?

Thanks! 

Related: https://github.com/facebook/react-native/issues/1157

**Comment by fkling** [comment]
I assume that whatever renders the docs is not set up to render unions. The output from react-docgen should be something like

```js
    "transform": {
      "type": {
        "name": "arrayOf",
        "value": {
          "name": "union",
          "value": [
            {
              "name": "shape",
              "value": {
                "rotation": {
                  "name": "number"
                }
              }
            },
            {
              "name": "shape",
              "value": {
                "scaleX": {
                  "name": "number"
                }
              }
            },
            {
              "name": "shape",
              "value": {
                "scaleY": {
                  "name": "number"
                }
              }
            },
            {
              "name": "shape",
              "value": {
                "translateX": {
                  "name": "number"
                }
              }
            },
            {
              "name": "shape",
              "value": {
                "translateY": {
                  "name": "number"
                }
              }
            }
          ]
        }
      },
      "required": false,
      "description": ""
    }
  }
```

So all you have to do is iterate over `value` and build the output you want.

**Comment by brentvatne** [comment]
Thanks! Fixed here: https://github.com/facebook/react-native/pull/1181

**Comment by fkling** [comment]
Awesome!

**Comment by mikeaustin** [comment]
I'm using styleguidist which uses react-docgen, but it still outputs "union" for Flow types such as ("foo" | "bar"). Is there a plugin or patch or something to make it list the union types?

I realize this in an old thread, but if there is an answer, I assume it would be useful to others.
