### ISSUE TITLE
Similiar Project, maybe helpful for es6 classes

### ISSUE THREAD

**Issue by jquense** [reactjs/react-docgen#14]
Hi there,

First thanks for the excellent work. Second, I was teaching myself how to work with a js AST and messing with the babel plugin system and thought extracting metadata from React components would be a good project to start with. The result being that I've implemented a lot of the same functionality as react-docgen as a babel plugin, including support for ES6 classes (normal and with property initializer syntax).

I realize that the work isn't compatible with Recast but since the underlying AST nodes defs are the same, I thought perhaps it might be helpful as a reference starting point for anyone who wanted to implement es6 class support in react-docgen. I know I benefited a lot from looking at how react-docgen worked in my little project. I never intended this weekend project to be maintained or useful as a tool, so hopefully someone here may get some benefit from it :)

O and here is the link to the repo: https://github.com/jquense/react-component-metadata

**Comment by fkling** [comment]
Thanks for the info! I'm closing this since there is nothing actionable here.
