### ISSUE TITLE
Adding @param to a function property

### ISSUE THREAD

**Issue by jsantana90** [reactjs/react-docgen#141]
I'm trying to document the parameters that you are able to pass in a property

```
/**
 * Redux action to set the the current pagination.
 * @param {number} from - Default value is 0
 * @param {number} to - Default value is 6
 */
setPagination: PropTypes.func.isRequired
```

but doesn't seem to add it in the generated json file

```
"setPagination": {
  "type": {
    "name": "func"
  },
  "required": true,
  "description": "Redux action to set the the current pagination.\n@param {number} from - Default value is 0\n@param {number} to - Default value is 6"
}
```

**Question**

How can I add the parameters in the documentation?

**Comment by fkling** [comment]
react-docgen doesn't apply any specific treatment to the docblock of propTypes. The raw content is in the `description` field. You can use any tool of your choice to extract additional information from that.

**Comment by jsantana90** [comment]
ah alright, thanks!
