### ISSUE TITLE
Proposal: Support inline comments for prop-type descriptions

### ISSUE THREAD

**Issue by withinboredom** [reactjs/react-docgen#148]
A lot of code currently in existence doesn't use jsdoc blocks to document proptypes (at least in my experience). For example:

``` js
propTypes: {
		theme: React.PropTypes.shape( {
			// Theme ID (theme-slug)
			id: React.PropTypes.string.isRequired,
			// Theme name
			name: React.PropTypes.string.isRequired,
			// Theme screenshot URL
			screenshot: React.PropTypes.string,
			// Theme price (pre-formatted string) -- empty string indicates free theme
			price: React.PropTypes.string,
			author: React.PropTypes.string,
			author_uri: React.PropTypes.string,
			demo_uri: React.PropTypes.string,
			stylesheet: React.PropTypes.string
		} ),
		// If true, highlight this theme as active
		active: React.PropTypes.bool,
		// If true, the user has 'purchased' the theme
		purchased: React.PropTypes.bool,
		// If true, the theme is being installed
		installing: React.PropTypes.bool,
		// If true, render a placeholder
		isPlaceholder: React.PropTypes.bool,
		// URL the screenshot link points to
		screenshotClickUrl: React.PropTypes.string,
		// Called when theme screenshot is clicked
		onScreenshotClick: React.PropTypes.func,
		// Called when the more button is clicked
		onMoreButtonClick: React.PropTypes.func,
		// Options to populate the 'More' button popover menu with
		buttonContents: React.PropTypes.objectOf(
			React.PropTypes.shape( {
				label: React.PropTypes.string,
				header: React.PropTypes.string,
				action: React.PropTypes.func,
				getUrl: React.PropTypes.func
			} )
		),
		// Index of theme in results list
		index: React.PropTypes.number,
		// Label to show on screenshot hover.
		actionLabel: React.PropTypes.string
	},
```
from [wp-calypso](https://github.com/Automattic/wp-calypso/blob/master/client/components/theme/index.jsx#L22-L64)

Basically:

- An inline comment before a proptype, belongs to the following proptype
- An inline comment after a proptype, and only on the same line, belongs to the previous proptype

Thoughts?

**Comment by fkling** [comment]
In general we don't want to add new handlers that do not cover a core React feature.

But that doesn't mean you have to go without such a feature! react-docgen is extensible, so you can build your own handler that provides this functionality.

Have a look [at the current prop doc handler](https://github.com/reactjs/react-docgen/blob/691e3b63b7b2187030ec3b9a526e2c2c2bca1df7/src/handlers/propDocBlockHandler.js) and [`react-docgen-displayname-handler`](https://github.com/nerdlabs/react-docgen-displayname-handler) for an example of an external handler.

Let me know if you have any questions about it!
