### ISSUE TITLE
Error thrown on constants import

### ISSUE THREAD

**Issue by avaly** [reactjs/react-docgen#150]
The following file is throwing an error on parse:

```js
import React, { Component, PropTypes } from 'react';
import { SMALL, LARGE } from './sizes';

class Test extends Component {
  render() {
    return <div />;
  }
}

Test.propTypes = {
  size: PropTypes.oneOf([SMALL, LARGE]),
};

export default Test;
```

Output:

```
Error with path "bug-import.js": Error: [{type: ImportSpecifier, start: 62, end: 67, loc: [object Object], imported: [object Object], local: [object Object], id: null, name: null}, {type: ImportSpecifier, start: 69, end: 74, loc: [object Object], imported: [object Object], local: [object Object], id: null, name: null}] does not match type Printable
```

If the second import line is commented out, it doesn't throw an error on parse, but the values for the constants are set to their names as string.

Using `react-docgen` v2.13.0

**Comment by dgarofalo** [comment]
I had the same problem important constants from an npm package.

```
// Constants.js
module.exports = {
    FOO: 'bar',
    OTHER_FOO: 'bar'
};
```

Importing the constants as named imports only worked if I imported one thing. I updated the syntax to use a default import, and then destructured it like so:

```
import Constants from './Constants';

const {
	START_DATE,
	ANCHOR_LEFT,
	ANCHOR_RIGHT
} = Constants;
```

**Comment by fkling** [comment]
Sorry, I completely missed that issue. This seems to be a problem with recast. I will see if this can be worked around on our side.

**Comment by jboelen** [comment]
Had to do the same as dgarofalo to get past this issue.
```jsx
import * as Constants from './constants';
const { VIEW, EDIT, DELETE } = Constants;
```

**Comment by priley86** [comment]
+1
