### ISSUE TITLE
support `Object.keys` within `oneOf`

### ISSUE THREAD

**Issue by chrisdrackett** [reactjs/react-docgen#153]
I'd like to use `Object.keys` to generate the list of values possible for `oneOf` but have found that this currently does not work. Has anyone run into this before? Not sure if this is a feature request or if there is a better way I could be writing my propType.

**Comment by fkling** [comment]
Can you give a concrete example and the result you expect? We could certainly special case `Object.keys`, but only if the passed value can also be statically resolved to an object literal.

**Comment by chrisdrackett** [comment]
sure, this is what I'm doing:


In an external file that is shared by a couple components:
```
const status = {
  info: {
    color: 'gray',
    icon: 'info',
  },
  normal: {
    color: 'green',
    icon: 'check',
  },
  warning: {
    color: 'orange',
    icon: 'warning',
  },
  error: {
    color: 'red',
    icon: 'x',
  },
}

const statusValues = Object.keys(status)
```

In a component that accepts one of the statuses listed above:
```
status: PropTypes.oneOf(statusValues)
```

I'm looking for the list `['info', 'normal', 'warning', 'error']`

**Comment by fkling** [comment]
`react-docgen` doesn't analyze code across files... however, depending on what exactly you are doing with react-docgen, you could get the list of keys in a different way (e.g. by actually loading that file) and insert the values into the documentation object that react-docgen produces.

**Comment by chrisdrackett** [comment]
also, of note, I did just try and do this with an object in the same file and I still get this output. So while this might not ever work for an object from an external file it might still be nice for something within the same file.

**Comment by fkling** [comment]
Yeah, that's what I meant when I said that we could special case `Object.keys(<resolves to object literal>)` being passed to `.oneOf`.

**Comment by chrisdrackett** [comment]
ah, right, I have the memory of a goldfish. carry on!

**Comment by motleydev** [comment]
I would like this as well. Seems that variables should be evaluated before the docs get "scraped" from the file.

**Comment by MaxInMoon** [comment]
+1

**Comment by dmitry-zaets** [comment]
Related to https://github.com/reactjs/react-docgen/issues/153

**Comment by andreapiras** [comment]
If props are imported from external file, values are still not displayed. 
You get something like this  "value": "status"
Is there any workaround for this?

**Comment by gaurav5430** [comment]
any updates on this?

Object.keys seems to work if the object is declared in the same file, but not when imported.

Would this be fixed when https://github.com/reactjs/react-docgen/pull/352 is merged ?

**Comment by DorianMaliszewski** [comment]
Up, I have the same problem ! :)
