### ISSUE TITLE
Add support for displayName

### ISSUE THREAD

**Issue by theogravity** [reactjs/react-docgen#16]
Hi there,

Thanks for `react-docgen`, it's been really handy so far in being able to document our component props. We have a use case where we want to associate the generated documentation against the component's `displayName` instead of the filename, and cannot do so without requiring the component in question to obtain it (which can kill build time with more components).

Would like to request that `displayName` be added to the generated doc, please!

**Comment by fkling** [comment]
Yes, that should be easy to do. You could write your own resolver if you need it quickly, but I'll include it in the next release.

**Comment by theogravity** [comment]
Thank you :D

(Hope you've checked out the `react-styleguide-generator` issue I have, it shows what I'm trying to do with `react-docgen`!)

**Comment by theogravity** [comment]
Thank you so much, was able to obtain the `displayName`
