### ISSUE TITLE
Collect contextTypes the same way as propTypes

### ISSUE THREAD

**Issue by andyearnshaw** [reactjs/react-docgen#167]
I'm hoping to get support for this in BlueKit, but it relies on react-docgen to collect the props.  I'm developing a library that uses context to pass theme (and some other props) through to descendant components.

`contextTypes` work the same way as `propTypes`, so it should be possible to reuse the code.

Edit: looks like there's a dead PR for this already, https://github.com/reactjs/react-docgen/pull/130.

**Comment by danez** [comment]
This will be in 3.0.0
