### ISSUE TITLE
Support for flowtype exact object notation

### ISSUE THREAD

**Issue by joris974** [reactjs/react-docgen#173]
Is there a way to be able to parse flow types when using [exact object notation](https://flow.org/en/docs/types/objects/#toc-exact-object-types)?

```js
/* @flow */

import React from "react"

type Props =
  {| foo: string |}

class Foo extends React.Component<void, Props, void> {
  render() {
    return "test"
  }
}
```
The error I receive when running `react-docgen foo.js` is 
```
Error when parsing foo.js: SyntaxError: Unexpected token (6:3)
```
It works like a charm when removing the exact object notation:
```js
type Props =
  { foo: string }
```

**Comment by fkling** [comment]
Have you tried using the v3 beta (might not work, just curious)?

**Comment by joris974** [comment]
It is working well with `v3` beta. It makes sense, `babylon` supports flow exact object notation starting at `6.10.0` and `react-docgen@2.14.0` uses `babylon@5.8.38`. The beta v3 uses `babylon@7.0.0-beta.8`.
I guess I will just wait a bit for stable v3.
Thank you for your help @fkling.

**Comment by kevinbarabash** [comment]
Although upgrading the parser will support the basic notation, often times you'll want to combine types using spread notation which means code changes are necessary for full support.  Here's an example:
```
type Foo = {|foo: string|};
type Bar = {|bar: number|};
type FooBar = {|
   ...Foo,
   ...Bar,
|};  // same as {|foo: string, bar: number|}
```
