### ISSUE TITLE
Issue with transpiled code in v2.14.0 vs v2.13.0

### ISSUE THREAD

**Issue by ryanthemanuel** [reactjs/react-docgen#174]
We ran into an issue when we upgraded to v2.14.0 today that was not existing in v2.13.0.  Specifically this issue was hit when running our continuous integration night watch tests against PhantomJS.  We are seeing a console error: 'SyntaxError: Unexpected token '['' that maps to this line of code: https://github.com/reactjs/react-docgen/blob/d65bfc460d7274206c3208fc41518727acd5a490/src/utils/getMemberValuePath.js#L25  It appears that PhantomJS is not set up to use the new syntax for declaring objects.  I'm not sure what transpiling happened in v2.13.0 that is not happening in v2.14.0, but there is definitely something different between the two.

**Comment by fkling** [comment]
da97fc6973d9cea1f52f7b334f82f1501997b886 made a change to use `preset-env` with Node v4 as target (instead `preset-es2015`). Sorry for that! We could switch back, but of course we to transpile as few code as possible. Usually I would recommend to perform your own transpilation if you need to run it in an unsupported environment.

cc @danez

**Comment by danez** [comment]
Uppss, I thought react docgen was already requiring node4 at least. I go ahead and revert it for 2.x. but I would leave it for 3.x.

**Comment by fkling** [comment]
I released v2.14.1 with @danez' changes. Let me know if that works for you!

**Comment by ryanthemanuel** [comment]
I just tested the 2.14.1 release and it works for us.  Thanks!
