### ISSUE TITLE
Please support the i18n title/description for the property name.

### ISSUE THREAD

**Issue by janryWang** [reactjs/react-docgen#184]
like this

```
/*
   @title(zh-cn): 这是AA组件
   @description(zh-cn): 这是AA组件的描述
*/
class Dialog extends Component {
     static propTypes = {
          /*
               @title(zh-cn)：是否打开
               @description(zh-cn)：主要在组件受控状态下来控制弹窗的显示与隐藏
          */
          isOpen:React.PropTypes.bool

    }

}

```

**Comment by fkling** [comment]
I'm not sure what it is exactly that we are supposed to do here. Can you clarify?

**Comment by janryWang** [comment]
I hope that the document can support the automated generation of multi-language versions

**Comment by sonsoleslp** [comment]
I also think this would be a neat feature: being able to describe the same proptype in several language in order to automatically generate docs in several languages.
Something like:
MyComponent.propTypes = {
    /**
    * @es Indica si el componente está oculto
   *  @en Indicates whether the component is hidden or not
    */
    disabled: PropTypes.boolean,
  };

**Comment by fkling** [comment]
@sonsoleslp: You can already do that. The full description is preserved. You can extract the different languages and generate the documentation you want from it.
