### ISSUE TITLE
Is possible to generate doc with imported component

### ISSUE THREAD

**Issue by intelcoder** [reactjs/react-docgen#185]
I want to get generated doc in javascript. However, parse function does not seem to work or i do not know how to use properly.

`import { SimpleButton } from 'Buttons'`

What I want to do is exactly code below
`const json = docGen.parse(SimpleButton);``
`

**Comment by fkling** [comment]
react-docgen does not parse dependencies. See #33, #73, #180 for similar issues. If you want to get the documentation for `SimpleButton`, you should pass the file where the `Buttons` module is defined.

**Comment by intelcoder** [comment]
So only way it can parse the component is that receiving path name?
What I can do is like below ?
`const json = docGen.parse(Path, resolver);`

**Comment by pasupuletics** [comment]
@intelcoder, is your import and docgen.parse in same file? If yes doc gen doesn't understad this. Src code must be strong.

**Comment by pasupuletics** [comment]
String
