### ISSUE TITLE
Open to a resolver for styled-components?

### ISSUE THREAD

**Issue by nickbreaton** [reactjs/react-docgen#187]
Hello! Thanks for all the hard work on react-docgen!

I have a small issue that I would be will to help fix. The [styled-components](https://www.styled-components.com/) library does not use React syntax to generate components:

```jsx
const GreenButton = styled.p`
  color: green;
`;
```
But can still be rendered as a React component:
```jsx
<GreenButton/>
```

Would you all be open to a PR to add this as a supported type of component? Would it be better to implement this as an external library? I believe there is [demand](https://github.com/styleguidist/react-styleguidist/issues/37#issuecomment-263502454) for this with a library that depends on react-docgen.

Thanks again!

**Comment by fkling** [comment]
Hey Nick!

I don't think it would beneficial to include this into the core. I wouldn't have the capacity to maintain it and it would make it harder for others (you I guess) to maintain it.

react-docgen was built with custom extensions in mind, so I think an external package would make more sense, but I'd be happy to make changes to core as necessary to support this case.

**Comment by nickbreaton** [comment]
@fkling Thanks for getting back to me! I will go the route of trying to build out an extension.

**Comment by Jmeyering** [comment]
@fkling 

I've gone ahead and created a custom resolver which allows for annotated export declarations to be added to a definitions list. I've used this format.

```
const MyComponent = () => (
  <h1></h1>
);

// @component
export default MyComponent;
```

Ideally this would solve this styled-components issue and allow users to annotate their exported styled-components

The issue I'm running into is that `react-docgen` validates the types of definitions that are passed to the  [`getMemberValuePath.js`][https://github.com/reactjs/react-docgen/blob/master/src/utils/getMemberValuePath.js#L35] function and limits them to a list which does not include `TaggedTemplateExpression`.

I'm willing to create a lookup method for `TaggedTemplateExpression` but was wondering if there was any information I should know before I went down that road too far.

**Comment by fkling** [comment]
That's great @Jmeyering! `getMemberValuePath` is supposed find specific "members" of a component, e.g. `propTypes`.

Given a component such as 

```js
const GreenButton = styled.p`
  color: green;
`;
```

it's only possible to add additional propTypes by doing

```js
GreenButton.propTypes = ...;
```

(whether or not that is something that is usually done is irrelevant for this discussion)

Maybe it would make sense to default any unknown expression to `getMemberExpressionValuePath` (which would have to be updated to support arbitrary expressions as well) ?

**Comment by Jmeyering** [comment]
Just submitted PR which uses `getMemberValuePath` when no other lookupMethod is available, it still does a type check, but I added `TaggedTemplateExpression` to be a valid type.

**Comment by Jmeyering** [comment]
@fkling Any idea if this approach is viable? If not I'm willing to try a more acceptable approach.
