### ISSUE TITLE
Parsing fails on exponentiation operator (**)

### ISSUE THREAD

**Issue by ambidexterich** [reactjs/react-docgen#188]
A defaultProp has a default value that uses the ** operator. Parsing fails with `Error when parsing <FILE_PATH>: SyntaxError: Unexpected token`.

Example:
```
static defaultProps = {
    value : 'Name',
    maxlength : 2 ** 19
}
```

**Comment by fkling** [comment]
Which version are you using? If you are using the latest public release, try the beta version instead. It uses a newer version of the babylon parser.

**Comment by ambidexterich** [comment]
I am using 2.15.0, I will check out the beta and l let you know.

**Comment by ambidexterich** [comment]
It works properly with v3.0.0-beta4

**Comment by fkling** [comment]
OK, I have to spend some time again to see if we can release v3.
