### ISSUE TITLE
parameters for react-docgen

### ISSUE THREAD

**Issue by peterjwlee** [reactjs/react-docgen#192]
Hi I am trying to call the react docgen api within my node application to generate documentation for my react components. I tried following the example on the ReadMe but i always get a No suitable component definition found even when I feed src the correct path to the file. I was browsing through the source code and found that the parse method takes in a handlers and resolvers parameter. However, I do not know what it means to customize the parse method. Any example in how people made their react components generate using javascript or node would be so helpful. I am having trouble in what to put in for resolvers or handlers.

**Comment by pasupuletics** [comment]
@peterjwlee , Sharing your example can help quickly look into the issue.

**Comment by fkling** [comment]
You can take a look at `src/handlers/` and `src/resolver/` to learn what kind of functions are accept.

*Resolvers* are functions that take the root of the AST as input and return one or more AST nodes that represent component definitions.

*Handlers* are functions that extract information from component definition nodes.

Both are briefly explained here: https://github.com/reactjs/react-docgen#parsesource--resolver--handlers .
