### ISSUE TITLE
Support Array destructuring for arguments

### ISSUE THREAD

**Issue by hlynurf** [reactjs/react-docgen#197]
The parse function throws a TypeError when a function has array destructuring for arguments.
Example:
```
onChangeSlider([min, max]) {
  this.setState({ min, max });
}
```
The error which is thrown is
`TypeError: Parameter name must be an Identifier, an AssignmentPattern an ObjectPattern or a RestElement, got ArrayPattern`
I can however get around this by destructuring inside the function instead.

**Comment by fkling** [comment]
Which version are you using?

**Comment by hlynurf** [comment]
2.16.0
Sorry, forgot to mention that.

**Comment by fkling** [comment]
Could you try the v3 beta version and see if that solves the problem for you?

**Comment by hlynurf** [comment]
Tried the 3.0.0-beta5 and I get the same error

**Comment by fkling** [comment]
OK, seems to be a mismatch with the parser and recast then.

**Comment by fkling** [comment]
Actually, after seeing the stack trace, it's an issue in our own `getParameterName` method. Easy fix!
