### ISSUE TITLE
/** Single-line jsdocs not supported */

### ISSUE THREAD

**Issue by marcello3d** [reactjs/react-docgen#20]
If I use the concise jsdoc syntax (all on one line):
```js
/** description of prop */
foo: React.PropTypes.any
```
I end up with `"description":""` in my output.

Changing it to 
```js
/** 
 * description of prop 
 */
```
or even
```js
/** 
 * description of prop */
```
works correctly (`"description":"description of prop"`).

**Comment by fkling** [comment]
Yes, it currently expects a line break after `/**`. I guess we could change that :)

**Comment by fkling** [comment]
Supported as of v2.1.0.
