### ISSUE TITLE
enum don’t understand in rect-docgen

### ISSUE THREAD

**Issue by konojunya** [reactjs/react-docgen#200]
I use react-docgen with [styleguidist/react-styleguidist](https://github.com/styleguidist/react-styleguidist). There is an error in the `enum` part.

error:

>Warning: Cannot parse src/components/atoms/Button/index.tsx: SyntaxError: Unexpected token (8:12)
>
>It usually means that react-docgen don’t understand your source code, try to file an issue here:
>https://github.com/reactjs/react-docgen/issues

I searched for an issue, but since I can not find anything like that, I made a new issue.

`src/components/atoms/Button/index.tsx` line 8

```ts
export enum ButtonType {
  Secondary,
  Primary,
  Notable,
  Warming,
  Negative,
  Disabled
}
```

It may be that you should use [styleguidist/react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript). However, because of this [issue](https://github.com/styleguidist/react-docgen-typescript/issues/30#issuecomment-318309829),
 [styleguidist/react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript) can not be used.

react-docgen version: `^2.17.0`

**Comment by danez** [comment]
react-docgen right now can only parse javascript and not typescript. There might be a way in the future as babylon - our parser - is getting typescript support, but right now there is nothing we can do here.

**Comment by konojunya** [comment]
I agree.
thanks :)
