### ISSUE TITLE
React.Node utility type is "unknown"

### ISSUE THREAD

**Issue by owiber** [reactjs/react-docgen#216]
[React.Node utility type](https://flow.org/en/docs/react/types/#toc-react-node) added in flow 0.53 is "unknown"

Example code:
```js
import * as React from 'react';

type Props = {
  content: React.Node,
};

class MyComponent extends React.Component<Props> {
  render() {
    return <div>{this.props.content}</div>;
  }
}

export default MyComponent;
```

react-docgen (3.0.0-beta7) output:
```
{
  "description": "",
  "methods": [],
  "props": {
    "content": {
      "flowType": {
        "name": "unknown"
      },
      "required": true,
      "description": ""
    }
  }
}
```

**Comment by fkling** [comment]
It looks like we don't support any of the `React.*` types. We probably have to special case them (cc @danez).

What else do we need to support besides `React.Node` ?

**Comment by danez** [comment]
I added a PR for this, it was fairly easy to add.
