### ISSUE TITLE
importing PropTypes from library for React v15.5.0+

### ISSUE THREAD

**Issue by rjbergerud** [reactjs/react-docgen#217]
It seems like docgen won't recognize proptypes declared as described in the [latest React docs](https://facebook.github.io/react/docs/typechecking-with-proptypes.html).

```
import PropTypes from 'prop-types';

class Greeting extends React.Component {
  render() {
    return (
      <h1>Hello, {this.props.name}</h1>
    );
  }
}

Greeting.propTypes = {
  name: PropTypes.string
};
```

**Comment by fkling** [comment]
Mmh, it should: https://github.com/reactjs/react-docgen/commit/d19d73d064cfa804157aa5afe979ba9e1ef8f6cb

**Comment by fkling** [comment]
This works for me: 

Input

```js
import PropTypes from 'prop-types';

class Greeting extends React.Component {
  render() {
    return (
      <h1>Hello, {this.props.name}</h1>
    );
  }
}

Greeting.propTypes = {
  name: PropTypes.string
};
```

Output:

```
{
  "description": "",
  "methods": [],
  "props": {
    "name": {
      "type": {
        "name": "string"
      },
      "required": false,
      "description": ""
    }
  }
}
```

**Comment by neutraali** [comment]
Can you make `react-docgen` assume that `prop-types` is always present instead of having to import it into every file? We use Webpack with global definitions for `react`, `react-DOM`, `prop-types` etc.
