### ISSUE TITLE
HELP!!!!!!! react-docgen's API parse is not useful

### ISSUE THREAD

**Issue by kamyzd** [reactjs/react-docgen#226]
const reactDocs = require('react-docgen')
var doc = reactDocs.parse('./src/Table/Table.js')

when I node this 
I get some error messages
![image](https://user-images.githubusercontent.com/12152855/31942903-85176e76-b88c-11e7-9ec2-1193f3e48f7d.png)

**Comment by danez** [comment]
The first parameter to the parse function is the sourcecode and not a path.

You would need to do something like this:

```
parse(fs.readFileSync('./src/Table/Table.js'));
```

**Comment by kamyzd** [comment]
Thank you so much!!   @danez
