### ISSUE TITLE
Parsing fails : empty array in defaultProps

### ISSUE THREAD

**Issue by sylvainar** [reactjs/react-docgen#234]
Hey!

When you provide an empty array as a default props, the parsing fail with a
 `Warning: Cannot parse src\react\components\research\resultList\ResearchResultList.jsx: AssertionError [ERR_ASSERTION]: false == true`

My code currently looks like this:

```javascript
import React from 'react';
import { FormattedHTMLMessage } from 'react-intl';
import PropTypes from 'prop-types';

export default class ResearchResultList extends React.PureComponent {
  static propTypes = {
    lines: PropTypes.arrayOf(PropTypes.shape({
      code: PropTypes.number,
      title: PropTypes.string,
      postCode: PropTypes.number,
      city: PropTypes.string,
    })),
    /** Array containing code of selected programs. */
    selectedPrograms: PropTypes.arrayOf(PropTypes.number),
    /**
     * Function that will be called when the action button is clicked.
     * @param {number} code - The program code.
     */
    onSelectProgram: PropTypes.func.isRequired,
  };

  static defaultProps = {
    lines: null,
    selectedPrograms: [],
  };

  render() {
    return (
      <p>{this.props.text}</p>
    );
  }
}
```

Thanks!

**Comment by danez** [comment]
I cannot reproduce this. Which version are you using? Are you sure this error comes from react-docgen? How do you use react-docgen?

**Comment by sylvainar** [comment]
We're actually using react-styleguidist, the error seems to come from docgen actually.

**Comment by sylvainar** [comment]
We find out the problem, it was because of the fact that we tried to use beta9 on styleguidist, and some functions of it were still using beta8 involving with weird behavior including this one.
I'm closing this issue!
