### ISSUE TITLE
oneOfType resolved as "custom"

### ISSUE THREAD

**Issue by pke** [reactjs/react-docgen#235]
This prop type definition

`const AmountType = PropTypes.oneOfType([PropTypes.number, PropTypes.string])`

results in a "custom" type when used. Is there no support for `oneOfType` yet? (Using 3.0.0.beta9 in [reac-styleguidist](https://github.com/styleguidist/react-styleguidist/blob/master/package.json#L74))

**Comment by danez** [comment]
We have tests that verify that this works. https://github.com/reactjs/react-docgen/blob/55bbefed8321d535e53786b684708bd618cc15fb/src/utils/__tests__/getPropType-test.js#L74

So not sure why this does not work in your case. Do you have a complete repro case?

**Comment by pke** [comment]
Interesting. Then maybe its a bug in how react-styleguidist works with the react-docgen ouput. I'll verify and re-open here if necessary.

**Comment by HarishSha** [comment]
Any update on this issue?
