### ISSUE TITLE
docgen crashing with Unexpected token (flow + prettier)

### ISSUE THREAD

**Issue by PDarkTemplar** [reactjs/react-docgen#236]
i have type like this:
```type Colors = 'text' | 'primary' | 'accent' | 'error' | 'success' | 'warning' | 'info' | 'additional' | 'minor';```
all working as expected.

If i turn on prettier with printWidth = 100 it will convert this line to:

```
type Colors =
    | 'text'
    | 'primary'
    | 'accent'
    | 'error'
    | 'success'
    | 'warning'
    | 'info'
    | 'additional'
    | 'minor';
```
which is perfectly valid flow type, but docgen can't understand first pipe and crashing.

**Comment by danez** [comment]
Please try using react-docgen@v3.0.0-beta. It should fix the issue.
version 2 uses an outdated parser that does not understand this syntax.

**Comment by PDarkTemplar** [comment]
That's helped, thanks.
