### ISSUE TITLE
self referencing flow type causing infinite loop

### ISSUE THREAD

**Issue by SavePointSam** [reactjs/react-docgen#249]
While using `react-styleguidist`, I noticed that I was getting this warning:

```
Warning: Cannot parse src/components/Button/Button.js: RangeError: Maximum call stack size exceeded

It usually means that react-docgen does not understand your source code, try to file an issue here:
https://github.com/reactjs/react-docgen/issues
```

While trying to debug this problem. I was having issues determining where the issue came from. I am using Flow to type my components out and Flow wasn't reporting an error. However, I learned that the issue was coming from the fact that I had a type that defined a method that had a parameter that was the parent typing. While this works fine in Flow, it appears to cause issues when running through `react-docgen`.

Here is a slimmed down representation of the problem: [Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MrgJ4ZGgCCFKWADtQAXlABvRKFDQSAIyLQAXKADOubCiEBzADSIQM4QFEAHkTIBXXEVUAKIgDciQ3KoDKHNwAsiuFDITFzcAHgAJABUAWQAZACEbXFNoIjRXXAA+PVAUWzRVfgDhAEoxTNAnWBQAEzZjIXNLGztQRxD3UBIhDhy8tMKBUvLK6pqDAF82RE5uUAAFagw1MUlpUGAAKk3QXD8uoaEVyBxd-as1Imxd2Fy3K-J8eDyfUE3gdcfBI8HioQBtAC6k2mW020h2vHU-lAsEgoHkSWEaghHzIyPwRW+Hhh4nsEgOfxWE1Ui1gyzKogq9k+hzUADo0CQMPZ7F9hH0hDUiGZKdT1jJQojcMkRMIAMLQQIAa1EEnaGT5hO+9NMFmstgVbhy7KEJQmmQFMkkuvpckU0AmRtCwGFosNMhKJUQJWmPKweFA3MgJCs0ExhxxuDYQA)

Note: You may need to swap the engine to `v0.64.0` or `master` as `v0.65.0` is [currently broken](https://github.com/facebook/flow/issues/5790)

**Comment by danez** [comment]
Thanks for reporting this. I was easily able to reproduce and fixed the issue in #251 and #252.

Will release a new version soon.

**Comment by matthew-dean** [comment]
This issue still occurs for me after updating `react-styleguidist` to version 7.3.9.

**Comment by SavePointSam** [comment]
I've also been experiencing it. It was never working correctly for me.

**Comment by matthew-dean** [comment]
Important note, `react-styleguidist` works with react-docgen 3.0.0-beta12, BUT react-docgen 3.0.0-beta6 AND react-docgen 3.0.0-rc.1 fail _in the same way_. 

That is, I get the error:

```
Warning: Cannot parse src/common/presentation/elements/Anchor/Anchor.js: RangeError: Maximum call stack size exceeded

It usually means that react-docgen does not understand your source code, try to file an issue here:
https://github.com/reactjs/react-docgen/issues

Warning: Cannot parse src/common/presentation/elements/Avatar/Avatar.js: RangeError: Maximum call stack size exceeded

It usually means that react-docgen does not understand your source code, try to file an issue here:
https://github.com/reactjs/react-docgen/issues
```

**Comment by ZxBing0066** [comment]
Please reopen this issue, cycles in propTypes still cause crashes.

For reproduction, copy the code below to the playground: https://reactcommunity.org/react-docgen/ .

```
import React, { Component } from 'react';
import PropTypes from 'prop-types';

/**
 * General component description.
 */
class MyComponent extends Component {
  render() {
    // ...
  }
}

MyComponent.propTypes = {
  /**
   * Description of prop "foo".
   */
  foo: PropTypes.number,
  /**
   * Description of prop "bar" (a custom validation function).
   */
  bar: function(props, propName, componentName) {
    // ...
  },
  baz: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.string
  ]).isRequired,
  child: PropTypes.shape(MyComponent.propTypes)
};

MyComponent.defaultProps = {
  foo: 42,
  bar: 21
};

export default MyComponent;
```
