### ISSUE TITLE
Support es6 import

### ISSUE THREAD

**Issue by penx** [reactjs/react-docgen#253]
This works for me:

```
const reactDocs = require("react-docgen");
...
reactDocs.parse(src)
```

I would expect the following to be equivalent:

```
import reactDocs from "react-docgen";
...
reactDocs.parse(src)
```

But I get the error:

```
Cannot read property 'parse' of undefined
```

react-docgen@2.20.1

**Comment by danez** [comment]
You have to do 

```
import { parse } from "react-docgen";
...
parse(src)
```

**Comment by stepancar** [comment]
@danez I think, we can close this issue

**Comment by penx** [comment]
Would still be useful to have parse as the default es6 export for anyone trying this in the future
