### ISSUE TITLE
Rename "description" to "docBlock" in output.

### ISSUE THREAD

**Issue by levithomason** [reactjs/react-docgen#26]
Currently the docblocks are added to the output json under the key `description`.  This makes sense if the only doclet in the docblock is a `@description`.  However, the value of `description` is the entire docblock string, which contains the actual description.

Given:

```jsx
import React from 'react';

/**
 * This is my thing.
 * @example
 * <Thing />
 */
export class Thing extends React.Component {
  render() {
    return <div />;
  }
}
```
When parsing and processing the `description` with a jsdoc parser ([doctrine](https://github.com/eslint/doctrine)) we get:

```json
{
  "description": {
    "description": "This is my thing.",
    "tags": [
      {
        "title": "example",
        "description": "<Thing />"
      }
    ]
  }
}
```

We access the docblock description (and other tags) through the `description` key.

```jsx
import thingInfo from './thingInfo.json';

thingInfo.description.description;            // This is my thing.
thingInfo.description.tags[0].title;          // example
thingInfo.description.tags[0].description;    // <Thing />
```

It may make more sense to rename the `description` to `docBlock`:

```jsx
import thingInfo from './thingInfo.json';

thingInfo.dockBlock.description;            // This is my thing.
thingInfo.dockBlock.tags[0].title;          // example
thingInfo.dockBlock.tags[0].description;    // <Thing />
```

___

For my usecase I can delete the description key and replace it with a docBlock key.  Though it is besides the point.  I think the above would be a semantic improvement for react-docgen.  Really excited about this project, by the way :) Thanks!

**Comment by fkling** [comment]
Mmh. Overall I would agree, but the added value doesn't really justify a breaking change. I'll leave this open for the next major version.

**Comment by levithomason** [comment]
:+1:

**Comment by mik01aj** [comment]
@levithomason maybe you would consider using a tool like [react-styleguidist](https://github.com/sapegin/react-styleguidist/) that reads your examples from Markdown files? I personally like this approach more.

**Comment by levithomason** [comment]
@mik01aj Thanks for the suggestion.  I ended writing a gulp plugin that leverages react-docgen and [eslint/doctrine](https://github.com/eslint/doctrine) for docblock parsing.

As for examples, we're writing and rendering our examples as regular React components.  For the code snippet, we use webpack's [raw-loader](https://github.com/webpack/raw-loader) to read the text and highlight it with [react-highlightjs](https://github.com/akiran/react-highlight).  This is working pretty well for us so far.

**Comment by fkling** [comment]
Looking back at this, I don't think that a minor improvement in code aesthetics justifies a breaking change. You can always renamed the property yourself before you process it further.

I'm going to close this for now. If anybody feels really strongly about this, please let me know.
