### ISSUE TITLE
Flow | Prop info not showing with React Types when importing specific types from react

### ISSUE THREAD

**Issue by codequistador** [reactjs/react-docgen#262]
### Issue details

I'm using Flow in my project. Some of my components work fine while others fail to generate prop information. Here is what I've narrowed it down to.

If I do this:

```js
import React, {
  PureComponent,
  type Node as ReactNode
} from 'react'
```
plus
```js
export default class ComponentX extends PureComponent<{
  children?: ReactNode,
  label?: ReactNode
}>
```
I don't get prop info for ComponentX

But if I do this:

```js
import * as React from 'react'
``` 
plus
```js
export default class ComponentX extends PureComponent<{
  children?: React.Node,
  label?: React.Node
}>
```
I get prop info for ComponentX.

According to these docs this is a supported way of doing imports of types: https://flow.org/en/docs/react/types/

**Comment by danez** [comment]
Which version react-docgen are you using? I just tried to reproduce but all of these examples work for me on the latest v3 beta version.
