### ISSUE TITLE
Warning: Cannot parse svg/brand.svg: SyntaxError: Unexpected token (1:1)

### ISSUE THREAD

**Issue by kopax** [reactjs/react-docgen#263]
I have a package that use react-styleguide and react-docgen, but without any react-component.

Instead, we use `svgr` and I try to import a svg as a react-component.

This work fine but it generate warning:

```
⠸ Compiling...Warning: Cannot parse svg/brand.svg: SyntaxError: Unexpected token (1:1)

It usually means that react-docgen does not understand your source code, try to file an issue here:
https://github.com/reactjs/react-docgen/issues

 DONE  Compiled successfully!

```

Is there a way to disable thoose ?

**Comment by fkling** [comment]
Maybe this should be raised with `react-styleguide`. We could certainly add a silent mode, but it would still be on `react-styleguide` to enable that mode. Or they should not apply react-docgen to things that are not react components.
