### ISSUE TITLE
Flow unions and spread operators cause parse failure

### ISSUE THREAD

**Issue by jonthomp** [reactjs/react-docgen#266]
We have 4 types, each containing a union. These 4 are then spread into a 5th type, however, using spread operators for this results in an error with react-docgen.

Build error received: `Warning: Cannot parse src/components/Text/Text.react.js: TypeError: Argument must be an Identifier or a Literal`

We're using react-styleguidist too. In case it helps, the error that's appearing instead of our components is: `TypeError: Failed to construct 'Text': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`

Example types:
```jsx
type AlignProps = {|
  +align?: "left" | "center" | "right" | "justify",
  +left?: boolean,
  +center?: boolean,
  +right?: boolean,
  +justify?: boolean,
|};

type TransformProps = {|
  +transform?: "lowercase" | "uppercase" | "capitalize",
  +lowercase?: boolean,
  +uppercase?: boolean,
  +capitalize?: boolean,
|};

type TrackingProps = {|
  +tracking?: "tight" | "normal" | "wide",
  +trackingTight?: boolean,
  +trackingNormal?: boolean,
  +trackingWide?: boolean,
|};

type LeadingProps = {|
  +leading?: "none" | "tight" | "normal" | "loose",
  +leadingNone?: boolean,
  +leadingTight?: boolean,
  +leadingNormal?: boolean,
  +leadingLoose?: boolean,
|};

type TextProps = {|
  ...AlignProps,
  ...TransformProps,
  ...TrackingProps,
  ...LeadingProps,
  +children?: React.Node,
  +className?: string,
  +RootComponent?: React.ElementType,
  +color?: string,
  +size?: string,
  +wrap?: boolean,
  +muted?: boolean,
|};
```

**Comment by danez** [comment]
Please try using v3.0.0-beta. I could not reproduce the error with the latest beta. I also added a test to ensure it works.
