### ISSUE TITLE
Cannot parse dynamic prop types

### ISSUE THREAD

**Issue by r3dcrosse** [reactjs/react-docgen#270]
When defining a propType such as:
```
DogeChart.propTypes = {
  /** Data Key used to accumulate number of doges */
  dataKey: PropTypes.string.isRequired,
  /** Data array of doge objects */
  dogeData: PropTypes.arrayOf(PropTypes.shape({
    /**
     *  The dataKey will pull out the number from this key
     *  and the number will be summed according to it's key, 
     *  then divided by the largest keyed sum from the data array.
     */
    [PropTypes.string]: PropTypes.number,
  }).isRequired,
};
```
I get the error:
```
Warning: Cannot parse js/src/components/DogeChart/index.jsx: TypeError: Propery name must be an Identifier or a Literal

It usually means that react-docgen does not understand your source code, try to file an issue here:
https://github.com/reactjs/react-docgen/issues
```

This error appears to be thrown by the dynamic prop type: `[PropTypes.string]`.

One would argue that normalizing data would make it so we wouldn't need to use a dynamic prop type, however I feel like this should still work, or at least skip the problem key and continue on. 

I'm open to discussing the expected behavior when using a dynamic prop type. 

Lastly, thank you for putting together and maintaining this awesome repo!

**Comment by danez** [comment]
```
dogeData: PropTypes.arrayOf(PropTypes.shape({
    /**
     *  The dataKey will pull out the number from this key
     *  and the number will be summed according to it's key, 
     *  then divided by the largest keyed sum from the data array.
     */
    [PropTypes.string]: PropTypes.number,
  }).isRequired,
```

I'm not sure, but I have never seen this construct before. Are you sure this works correctly?
Also briefly looking at the source of the prop-types package does not reveal that computed object keys will work.
