### ISSUE TITLE
Support for `PropTypes.exact`

### ISSUE THREAD

**Issue by jtomaszewski** [reactjs/react-docgen#309]
Why don't we support `PropTypes.exact` in the same way as we do `PropTypes.shape` ? Is there any reason behind it?

Implementing it would be probably very easy, as it's `exact` is almost the same as `shape`. (I could do PR for it maybe.)

**Comment by danez** [comment]
I think there is no reason behind this. Maybe it did not exist when PropTypes were implemented here.

Feel free to create PR and add it, as you say it should be straight forward to do it, as it is similar to `shape`.

**Comment by jtomaszewski** [comment]
OK, will do that! Give me a couple of days and I'll submit it.

**Comment by danez** [comment]
Added in 52ae1f4
