### ISSUE TITLE
Description null for properties of components wrapped in forwardRef HOC

### ISSUE THREAD

**Issue by codylawson** [reactjs/react-docgen#312]
Seeing an issue where wrapping a component in `forwardRef` results in the descriptions resolving to `null`.

Works:
```
import PropTypes from 'prop-types';
import React from 'react';

const Label = ({ children, ...other }) => {
  return <div {...other}>{children}</div>;
};

Label.propTypes = {
  /** Content of the label */
  children: PropTypes.node,
  /** Blue style label */
  blue: PropTypes.bool,
  /** Green style label */
  green: PropTypes.bool,
  /** Yellow style label */
  yellow: PropTypes.bool,
  /** Red style label */
  red: PropTypes.bool
};

Label.defaultProps = {};

export default Label;
```

Broken:
```
import PropTypes from 'prop-types';
import React, {forwardRef} from 'react';

const Label = forwardRef(({ children, ...other }, ref) => {
  return <div {...other} ref={ref}>{children}</div>;
});

Label.propTypes = {
  /** Content of the label */
  children: PropTypes.node,
  /** Blue style label */
  blue: PropTypes.bool,
  /** Green style label */
  green: PropTypes.bool,
  /** Yellow style label */
  yellow: PropTypes.bool,
  /** Red style label */
  red: PropTypes.bool
};

Label.defaultProps = {};

export default Label;
```

It's interesting that the rest of the prop definition exists and only the description is dropped. Is this a known issue? It seems slightly different from other issues related to HOC in that even if the component name is resolved correctly, the prop definition is not complete.

**Comment by danez** [comment]
This was fixed in #311 and 3.0.0-rc.2. Can you try with this version?

**Comment by codylawson** [comment]
@danez Confirmed to fix the issue I was seeing. This can be closed.

To followup though, it looks like the fix required a special handler for `forwardRef` as a known hoc. Does that mean all hoc's would need to be handled specially? Are custom hoc's not supported?

**Comment by eps1lon** [comment]
@codylawson `forwardRef` is not a HOC but a "normal" component. The issue was that `forwardRef` was not considered a component and therefore not eligible for HOC wrapping.
