### ISSUE TITLE
Allow passing parser options

### ISSUE THREAD

**Issue by jquense** [reactjs/react-docgen#316]
Hey there 👋 Wondering if you'd be open to allowing babel/parser options to be passed through or respect the local babelrc. I'd love to write a typescript handler for react-docgen built off the v7 TS support but at the moment that's not as easy as it could be because the parser is defaulted to `flow`.

**Comment by danez** [comment]
The best option would be to use 
```
require('@babel/core').parse(...)
```
As this will pickup the babel configuration that is present in the project. With some sane fallback config (basically what we have right now).
Exposing the config would be good I guess, I think I already do it for the decorators plugin.

Typescript support would be awesome.
