### ISSUE TITLE
dynamic context type names fail the whole file

### ISSUE THREAD

**Issue by giladv** [reactjs/react-docgen#317]
3.X

dynamic context type names fail the whole file 
```
static contextTypes = {
    [DYNAMIC_NAME]: ...
}
```

```
TypeError: Property name must be an Identifier or a Literal

```

why fail the entire file?
a warning + moving to the next prop/context type should be the way to go.

thanks.

**Comment by wwsun** [comment]
any solutions?

**Comment by priley86** [comment]
bumping up against this one too. Any chance we can suppress this?
