### ISSUE TITLE
Can I help maintain react-docgen?

### ISSUE THREAD

**Issue by jquense** [reactjs/react-docgen#319]
Hi @danez I use react-docgen in almost every project I work on either for tooling or to help with documentation. I maintain the Gatsby plugin for react-docgen and a have written a bunch of resolvers and handlers for work and OSS. I'd love to help out with the core project and help move some of the issues along as well as work on some new features like better typescript integration. It seems like you don't have a ton of time of to work on this which is definitely a position i understand, I've plenty of projects that aren't super relevant to my work or life any more and can't put the time in. I'm hoping you'd be open to sharing some of the responsibility in a way that makes your life easier as well as helping to move the project forward.

**Comment by fkling** [comment]
Any help is certainly appreciated @jquense!

**Comment by micahstubbs** [comment]
@fkling would be could to add a couple new maintainers with commit access so that the issue queue could get some love.  

here's a vote for adding @jquense as a maintainer with commit access to this repo, so that he can triage issues and review pull requests.

**Comment by danez** [comment]
@jquense I agree with @fkling and you do not necessarily need commit access to start working on new stuff.
I think we can all agree that introducing typescript support would be a huge win and I'm happy to help with reviewing or answering questions. You can usually always find me in the babel slack https://babeljs.slack.com/
