### ISSUE TITLE
Potential issue with findAllComponentDefinitions

### ISSUE THREAD

**Issue by fkling** [reactjs/react-docgen#331]
We have a component that looks something like this:

```jsx
/**
 * @flow
 */
import * as React from 'react';

type Props = $ReadOnly<{|
  tabs: $ReadOnlyArray<string>,
|}>;

const TetraAdminTabs = React.memo<Props>((props: Props) => (
  <div></div>
));

export default TetraAdminTabs;
```

When I run `react-docgen` normally I get the information for the component. If I use `--resolver findAllComponentDefinitions`. I get `Error: No suitable component definition found`.

I think `findAllComponentDefinitions` should be able to find the default exported one.

----

I'll investigate this myself but just wanted to post to keep track of it.

**Comment by pascalduez** [comment]
Same issue here, Flow + `forwardRef`. 
No props documented.

```
import * as React from 'react'

type Props = {
  children: string,
}

function Test(props, ref) {
  return <p>{props.children}</p>
}

export default React.forwarRef<Props, _>(Test)
```
