### ISSUE TITLE
Spread operator not parsed

### ISSUE THREAD

**Issue by tyanneolson** [reactjs/react-docgen#335]
Related to [Spread operator in default props](https://github.com/reactjs/react-docgen/issues/22) - the spread operator is not parsed in propTypes. 

eg:

```
class Tiger extends Cat {
  static get propTypes() {
    return {
      ...super.propTypes,
    }
  }
}
```

**Comment by fkling** [comment]
We may have a different understanding of what "parsed" means here. When I create a component with that method in http://reactcommunity.org/react-docgen/, it parses just fine. E.g. try this:

```
var foo = {
	bar: PropTypes.number,
};

/**
 * General component description.
 */
export class Tiger extends Component {
  static get propTypes() {
    return {
      ...foo,
      name: PropTypes.string,
    }
  }
  render() {}
}
```

However, react-docgen does not resolve dependencies.

**Comment by tyanneolson** [comment]
After further investigation my issue was related to something else, not the spread operator but a number of factors. Thanks for your response. Closing out.
