### ISSUE TITLE
Are there any tools to display (and search / filter) the resulting JSON?

### ISSUE THREAD

**Issue by bartvde** [reactjs/react-docgen#34]
Or do people write them from scratch? Any pointers?

**Comment by fkling** [comment]
Do you mean general tools for inspecting JSON or something that converts this specific JSON result to something renderable?

There is an example in https://github.com/reactjs/react-docgen/tree/master/example to convert the output to Markdown. There is also a docutils extension to convert it to reStructuredText: https://github.com/reactjs/react-docgen/wiki/Markup-generators

**Comment by bartvde** [comment]
Ah thanks, that's what I meant, what tools do people use to render this specific JSON structure.

**Comment by fkling** [comment]
I would certainly be happy about more examples as well though ;)
