### ISSUE TITLE
Output JSON format spec needed

### ISSUE THREAD

**Issue by mik01aj** [reactjs/react-docgen#35]
I have already tried 2 tools based on `react-docgen` and they fail on my code, because the JSON produced by `react-docgen` is different that they expect (for my cases, it was [because there was no `defaultValue`](https://github.com/sourcejs/sourcejs-react-docgen/issues/1#issuecomment-152229800) or [because `type.value` was a string](https://github.com/sapegin/react-styleguidist/issues/13#issuecomment-146868948)). In my opinion, these bugs happen because there is no spec of the ouptput JSON format, with some good examples to test in such styleguide tools. Help would be appreciated a lot.

**Comment by fkling** [comment]
There is a non-nominal spec in the README: https://github.com/reactjs/react-docgen#result-data-structure

The second issue you linked to seems to be a bug in `react-docgen`. `value` should be empty in that case (`raw` should be set instead).

**Comment by mik01aj** [comment]
@fkling thanks, I missed this description, sorry!

**Comment by fkling** [comment]
Well, it could be more extensive maybe :)

I'd appreciate it if you could file a bug for the second issue you mentioned!

**Comment by mik01aj** [comment]
About extensiveness: I think JSON schema could help. Then you would be able to verify that the JSON you return is really what you specified, and tool debelopers could use json-schema-random to generate examples and thus make them more reliable.
