### ISSUE TITLE
what happened to `utils.isReactForwardRefCall`

### ISSUE THREAD

**Issue by jacobbogers** [reactjs/react-docgen#359]
const docgen = require('react-docgen');
const { utils: { isReactForwardRefCall }  } = docgen

My code needs this function, I see there was a release last week, wich version is still using it?

**Comment by danez** [comment]
What's the error you are getting? The util is still exported as far as I can see.

Also which version are you mentioning?

**Comment by jacobbogers** [comment]
could it be related to this issue?
https://github.com/reactjs/react-docgen/pull/351

this is from node_modules/react-docgen/package.json
```
"name": "react-docgen",
  "version": "3.0.0",
```

**Comment by danez** [comment]
You have to use version 5.0.0-beta.1 to get `isReactForwardRefCall`

**Comment by jacobbogers** [comment]
Thank you
