### ISSUE TITLE
TypeScript mapped type support

### ISSUE THREAD

**Issue by ahutchings** [reactjs/react-docgen#361]
Docgen is outputting parsing TypeScript mapped types as `{name: 'unknown'}` . I've started putting together a change to add support for mapped types, but I'm not sure how we want to represent the type descriptor for it, since it's not a feature that Flow has. Does anyone have thoughts on how the type descriptor should be structured for something like this?

```typescript
var x: MyMappedType = {top: true};

type Side = 'top' | 'right' | 'bottom' | 'left';
type MyMappedType = { [side in Side]?: boolean};
```

cc @devongovett

**Comment by danez** [comment]
Isn't this the same as https://flow.org/en/docs/types/objects/#toc-objects-as-maps ?

**Comment by ahutchings** [comment]
Yep, looks like it is, and we can use the existing FlowObjectSignatureType to represent it. PR incoming shortly.
