### ISSUE TITLE
How to detect string source is Flow or TypeScript

### ISSUE THREAD

**Issue by guoyunhe** [reactjs/react-docgen#364]
I am using 5.0.0beta1.

If I pass a string of TypeScript to parse() function, it actually generates Flow types.

TypeScript:
```tsx
import "acux/core/button.css";
import classNames from "classnames";
import * as React from "react";

export interface ButtonProps
  extends React.DetailedHTMLProps<
    React.ButtonHTMLAttributes<HTMLButtonElement>,
    HTMLButtonElement
  > {
  size?: string;
  variant?: string;
  iconLeft?: React.ReactNode;
  iconRight?: React.ReactNode;
}

export default class Button extends React.Component<ButtonProps> {
  render() {
    const {
      className,
      children,
      size,
      variant,
      iconLeft,
      iconRight,
      ...rest
    } = this.props;
    return (
      <button
        className={classNames(
          "ac-button",
          size && "ac-button--size-" + size,
          variant && "ac-button--variant-" + variant,
          className
        )}
        {...rest}
      >
        {iconLeft && (
          <span className="ac-button__icon ac-button__icon--left">
            {iconLeft}
          </span>
        )}
        {children}
        {iconRight && (
          <span className="ac-button__icon ac-button__icon--right">
            {iconRight}
          </span>
        )}
      </button>
    );
  }
}
```

Generated types by `parse(source)`

```json
{"description":"","displayName":"Button","methods":[],"props":{"size":{"required":false,"flowType":{"name":"string"},"description":""},"variant":{"required":false,"flowType":{"name":"string"},"description":""},"iconLeft":{"required":false,"flowType":{"name":"ReactReactNode","raw":"React.ReactNode"},"description":""},"iconRight":{"required":false,"flowType":{"name":"ReactReactNode","raw":"React.ReactNode"},"description":""}}}
```

Maybe TypeScript is a more popular thing than Flow and can be set as default?

**Comment by danez** [comment]
You need to make sure that the file extension is actually `.ts` or `.tsx` and that your babelrc is correctly setup.

How are you using react-docgen? Do you set a custom config? react-dcogen should change between flow and ts based on the extension of the file as long as the default config is not overwritten.

Also I'm assuming you are using v5.0.0-beta.1. Version 4 does not support typescript.

**Comment by guoyunhe** [comment]
@danez I actually pass a string to `parse()`, which is loaded from Webpack raw loader. So it doesn't have a extension.

```js
import sourceCode from "!!raw-loader!../../../../../core/button.tsx";
import { parse } from "react-docgen";

const docsInfo = parse(sourceCode);
```

**Comment by danez** [comment]
You need to pass the filename with the options. https://github.com/reactjs/react-docgen#parsesource--resolver--handlers--options

Something like:

```js
parse(source, null, null, { filename: "button.tsx" });
```

**Comment by guoyunhe** [comment]
Thanks!

This works for me:
```js
parse(source, null, null, { filename: "button.tsx" });
```
I cannot use `path` because it is in browser environment. It seems you can provide any filename with `.tsx` extension, which doesn't have to be the same as your source code file.

**Comment by danez** [comment]
Yeah this works, as long as you don't need babel to resolve a config file. Babel is using the filename to know from where to resolve the babel config file.
