### ISSUE TITLE
Broken Example

### ISSUE THREAD

**Issue by MikeLockz** [reactjs/react-docgen#372]
The example at https://reactcommunity.org/react-docgen/ is returning **false** for  _foo: PropTypes.number.isRequired_

**Comment by fkling** [comment]
@danez explained this elsewhere, but if I remember correctly,  it's `false` because the component has a default value for that prop.

**Comment by MikeLockz** [comment]
@fkling - thanks for the quick response and I can understand why it would return false under that circumstance. 

Maybe updating the example to use the **isRequired** type on a different prop to demonstrate that it does return true when there is not a defaultProp.

**Comment by fkling** [comment]
Yeah, that makes sense.
