### ISSUE TITLE
ES5 and closures ...

### ISSUE THREAD

**Issue by rohan-deshpande** [reactjs/react-docgen#38]
Hi I'm wondering if it's still possible to use `react-docgen` when code is in the following format

```
 (function (app) {
    'use strict';
    /**
     * MyComponent description
     */
    app.components.MyComponent = React.createClass({
        //stuff;
    });
 }(app));
```

If so, how would I get it to work? I'm currently getting the following error ` Error: No suitable component definition found`.

**Edit** hmm well seems like I need to `var React = require('react');` at the top of the component which makes sense since `react-docgen` doesn't know about me including it via gulp, but yeah I think maybe this syntax won't work.

**Comment by fkling** [comment]
Sorry for the late reply. In this case you have to pass the `findAllComponentDefinitions` resolver to `reactDocgen.parse` or write your own. 

I should make this a command line option really.

**Comment by fkling** [comment]
I'm closing this for now since I do see any actionable item here. If you think there is something to do here, please reopen.
