### ISSUE TITLE
CLI: no way to replace default array values

### ISSUE THREAD

**Issue by isker** [reactjs/react-docgen#384]
The default arrays like https://github.com/reactjs/react-docgen/blob/e05219b08c8b17899be812a521b4985f2b66fae2/bin/react-docgen.js#L34 can only be appended to, not replaced, by passing values on the CLI.  This is most consequential for the one that I linked, as it's not possible to exclude '.js' files from processing except by adding an `--exclude` regex that overrides the default.

**Comment by danez** [comment]
Not relevant anymore with new CLI
