### ISSUE TITLE
Timeline for 5.0.0 release?

### ISSUE THREAD

**Issue by bryceosterhaus** [reactjs/react-docgen#399]
I was just curious if there was any ETA on the 5.0.0 release? I was using the beta, but realized I needed this fix for my ts project, https://github.com/reactjs/react-docgen/pull/392. Are there plans to release soon, or are there any particular issues that are blocking?

**Comment by josias-r** [comment]
I'm also curious because of [another issue](https://github.com/storybookjs/babel-plugin-react-docgen/pull/77)

**Comment by danez** [comment]
I released 5.0.0 just now. I does not include the resolving of imported files, because there are too many unknowns still.
