### ISSUE TITLE
react component propTypes object generate error

### ISSUE THREAD

**Issue by sundylink** [reactjs/react-docgen#405]
version  react-dcogen 5.0.0-beta.1

source :

![test](https://user-images.githubusercontent.com/35475866/69610658-3419bf80-1067-11ea-9adc-cee8ab1808b5.png)

generate json:

![image](https://user-images.githubusercontent.com/35475866/69610481-deddae00-1066-11ea-8933-2ea4a8cf3e2a.png)

how to fixed?

@sophiebits @wincent @zpao @tomocchino @threepointone

**Comment by danez** [comment]
This problem happens because PropTypes is never imported.
Is this valid code that works? Which means `PropTypes` is a global?
