### ISSUE TITLE
Failing test on travis with status 0

### ISSUE THREAD

**Issue by ondrejbartas** [reactjs/react-docgen#41]
Hi, 

look at travis, your tests are failing but travis is saying that build is ok.

**Comment by fkling** [comment]
Seems to look good for me: https://travis-ci.org/reactjs/react-docgen/builds/88383861 . What exactly are you referring to?

**Comment by fkling** [comment]
Maybe you meant that test are failing if you run them locally? I just fixed that with 546635c8c6e76aa70eb08e9f567652d67931fe5d .

**Comment by ondrejbartas** [comment]
I am reffering to: https://travis-ci.org/reactjs/react-docgen/builds/88382618 when you look at log you will see that tests failed but travis passed

**Comment by fkling** [comment]
Yep, that's because it was running in Node v5, hence I was only testing in v4 afterwards: https://travis-ci.org/reactjs/react-docgen/builds/88383861 . Either way, doesn't matter anymore. It was an issue with the test setup which is now fixed.

**Comment by fkling** [comment]
Regarding travis passing, I'm not sure why. I guess it has something to do with *how* the tests are failing.
