### ISSUE TITLE
Add markdown generator to bin

### ISSUE THREAD

**Issue by younabobo** [reactjs/react-docgen#411]
It would be good if it were possible to have the markdown generator script added to the binaries folder, this way it will be easier to generate a markdown file just from executing a simple command, I had made this executable myself before, might be useful as it parses both files and directories
https://github.com/younabobo/generate-react-doc

I have made a pull request concerning this: #412

**Comment by younabobo** [comment]
#412

**Comment by younabobo** [comment]
I think you've forgotten about this

**Comment by danez** [comment]
This is not part of this repository and only serves as an example
