### ISSUE TITLE
Add command line parameter for resolver

### ISSUE THREAD

**Issue by fkling** [reactjs/react-docgen#42]
`--resolver findAllComponentDefinitions` would use https://github.com/reactjs/react-docgen/blob/master/src/resolver/findAllComponentDefinitions.js.

`--resolver ./path/to/resolver.js` would use a custom resolver.

This allows to use another resolver without having to write a custom script.

**Comment by ondrejbartas** [comment]
nice :+1:

**Comment by vieron** [comment]
+1
