### ISSUE TITLE
support PropTypes rename ?

### ISSUE THREAD

**Issue by JieChang** [reactjs/react-docgen#437]
import T from 'prop-types';
static propTypes = {
    /**
     * 请求方式
     */
    method: T.oneOf(['GET', 'POST']),
}

**Comment by omniphx** [comment]
I'm also looking for a way to rename a prop type. For example, I'd like "forwardedRef" to always be called "ref". Is it possible to accomplish this with a resolver?

**Comment by danez** [comment]
We are not going to support any renaming as we just extract the data and any layer afterwards that uses the data can present/rename them in any way. The solution from @omniphx  should work.
