### ISSUE TITLE
Default Exported Component inlined in React.memo not recognized

### ISSUE THREAD

**Issue by FermiDirak** [reactjs/react-docgen#444]
This is not at all a critical issue, but I thought it'd be worth creating an issue for.

If a component definition is wrapped in React.memo and exported, docgen won't recognize it:

This doesn't work
```jsx
export default React.memo(function MyComponent() {
  return <div/>;
});
```

This works
```jsx
function MyComponent() {
  return <div/>;
}

export default React.memo(MyComponent);
```

This also works
```jsx
const MyComponent = React.memo(function MyComponent() {
  return <div/>;
})

export default MyComponent;
```

**Comment by JustFly1984** [comment]
This is incorrect use of React.memo

You need to define the component first, and 

export default React.memo(YourComponent);

If you setup Eslint with plugins, you will get warning that your way is incorrect
