### ISSUE TITLE
Correctly evaluate defaultValue and not only PropType.

### ISSUE THREAD

**Issue by oliviertassinari** [reactjs/react-docgen#45]
I have created a failing test to show you my issue: https://github.com/reactjs/react-docgen/pull/46.
The defaultValue is not extracted correctly.

**Comment by donnieberg** [comment]
@oliviertassinari +1 on this bug with ES6.
`MyComponent.defaultProps = { propName: "propVal" };`

**Comment by fkling** [comment]
Fixed with 27c9ec2fb4452a124502c7d2e3fb3d360ce58ef0 and published with v2.5.0

**Comment by oliviertassinari** [comment]
Thanks.
