### ISSUE TITLE
[TypeScript] Support for React.FC and SFC annotations

### ISSUE THREAD

**Issue by chrisdopuch** [reactjs/react-docgen#450]
I'm trying to migrate my project from `react-docgen-typescript` to `react-docgen` as part of migrating `react-styleguidist` to version 11.

Many of my components are typed like this:
```
const MyComponent: React.FC<MyComponentProps> = (props) => { ... };
```

This style of type annotation works correctly in `react-docgen-typescript` but `react-docgen` does not correctly pick up its typings. To test this I copy and pasted a test case from `react-docgen-typescript` into this repo and confirmed that no prop-types were generated for the component.

I created `react-docgen/src/__tests__/fixtures/component_33.tsx` with this content:
```
import * as React from "react";

/** JumbotronProps props */
export interface JumbotronProps {
  /** prop1 description */
  prop1: string;
}

/**
 * Jumbotron description
 */
export const Jumbotron: React.SFC<JumbotronProps> = props => {
  return <div>Test</div>;
};
```

And when I run the tests this is the output in the snapshot (note the lack of "props" attribute):
```
exports[`main fixtures processes component "component_33.tsx" without errors 1`] = `
Object {
  "description": "Jumbotron description",
  "displayName": "Jumbotron",
  "methods": Array [],
}
`;
```

This exact same test passes in `react-docgen-typescript` as seen here: https://github.com/styleguidist/react-docgen-typescript/blob/master/src/__tests__/data/ReactSFCAsConst.tsx

It would be amazing if `react-docgen` could also support the `React.FC / SFC` style of type annotation! 🙏 ❤️ 

Thanks for this great open-source library!

**Comment by Winner95** [comment]
Hello @chrisdopuch , 

I came across this problem before too, it was initially discussed [here](https://github.com/reactjs/react-docgen/issues/387). You can try to use [this custom handler](https://www.npmjs.com/package/typescript-react-function-component-props-handler) for react-docgen, hope it will help you.

**Comment by chrisdopuch** [comment]
Nice, thanks for the suggestion! I've actually refactored my codebase already to not use React.FC anymore though.

**Comment by chrisdopuch** [comment]
Closing as duplicate
