### ISSUE TITLE
Fatal Error when compiling

### ISSUE THREAD

**Issue by klimnikova** [reactjs/react-docgen#465]
Can't compiling a project.
Node version 12.8.3
MacOS
<--- Last few GCs --->
ce start of marking 21379 ms) (average mu = 0.126, current mu = 0.014[11116:0x102d4e000]   402874 ms: Mark-sweep 2035.9 (2056.5) -> 2029.4 (2054.0) MB, 21794.8 / 0.4 ms  (+ 136.8 ms in 70 steps since start of marking, biggest step 50.7 ms, walltime since start of marking 21945 ms) (average mu = 0.059, current mu = 0.001) a[11116:0x102d4e000]   422494 ms: Mark-sweep 2033.9 (2054.0) -> 2029.3 (2052.0) MB, 19606.0 / 0.5 ms  (average mu = 0.031, current mu = 0.001) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1009ce8d9]
Security context: 0x23844db808d1 <JSObject>
    1: get [0x2384dc708a11] [/Users/oksana/Desktop/project/node_modules/react-docgen/node_modules/ast-types/lib/path.js:~60] [pc=0x8667c5291fe](this=0x2384da85f6f9 <NodePath map = 0x2384a6233479>)
    2: arguments adaptor frame: 1->0
    3: getMembers(aka getMembers) [0x2384362e4981] [/Users/oksana/Desktop/projecti/node_modules/react-docgen/dist/ut...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1011bdf85 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x10009d569 node::Abort() [/usr/local/bin/node]
 3: 0x10009d6cf node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001de957 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001de8f7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100364635 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x100365e8a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x10036290e v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1003606c0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x10036c4ea v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x10036c571 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x10033a78a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
13: 0x100689858 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x1009ce8d9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by danez** [comment]
Nothing I can do here without an example.
