### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by metamn** [reactjs/react-docgen#469]
Hey :) 

I've just installed docgen with `yarn add react-docgen --dev`

Then imported it via `import { reactDocs } from "react-docgen";`

And I'm receiving: 

```
Failed to compile

./node_modules/@babel/core/lib/transformation/normalize-file.js
Module not found: Can't resolve 'fs' in '/home/cs/osequi/react-semantic-elements/node_modules/@babel/core/lib/transformation'

This error occurred during the build time and cannot be dismissed.
```

Thanks!

**Comment by hans2103** [comment]
@metamn I've stumbled upon this solution for a Next.js project

**next.config.js**
```
module.exports = {
  webpack: config => {
    // Fixes npm packages that depend on `fs` module
    config.node = {
      fs: 'empty'
    }

    return config
  }
}
```

**Comment by danez** [comment]
Yes this happens because babel has dependencies on some node modules. You can have a a look at the webpack config for our website, where we disable some of them: https://github.com/reactjs/react-docgen/blob/master/website/webpack.config.js#L92
