### ISSUE TITLE
Support Babel 6

### ISSUE THREAD

**Issue by oliviertassinari** [reactjs/react-docgen#47]
When using this module with a source code that is using babel 6.
I'm having this error:
```
TypeError: plugins.indexOf is not a function
```
This is from `webpack:///./~/babylon/lib/parser/index.js`:
```js
if (plugins.indexOf("flow") >= 0) { // At run time plugins is an object with {flow: true, jsx: true}
```
I guess that upgrading the version of [babylon](https://www.npmjs.com/package/babylon) would solve the issue.

**Comment by fkling** [comment]
What is the Babylon version you are using here? This rather seems to be a configuration error or an inconsistent state of your nodes_module folder. Sure, we could upgrade to a newer version of Babylon, but that shouldn't be necessary. Whatever Babel version you are using shouldn't impact react-docgen and vice versa.

**Comment by oliviertassinari** [comment]
> Whatever Babel version you are using shouldn't impact react-docgen and vice versa.

That's what I though, I'm gonna investigate more on this. 

> What is the Babylon version you are using here?

I'm using the latest release of react-docgen. I'm not using directly babylon.

**Comment by oliviertassinari** [comment]
@fkling Thanks for your help! It was indend an issue with my dependences. I had two version of babylon, and my webpack config wasn't resolving the good one :grin:.

**Comment by yrashk** [comment]
Is there any ETA for the Babel 6 upgrade? I am

**Comment by fkling** [comment]
@yrashk: There is no plan to upgrade babylon atm. Can you share information about your setup. You have to think of `react-docgen` as a standalone tool / library. Whatever setup you have shouldn't impact it, and there shouldn't be anything you have to configure differently.

However, there could be an issue when npm didn't install the correct dependencies. I guess one solution to avoid these issues could be to use [`bundleDependencies`](https://docs.npmjs.com/files/package.json#bundleddependencies).

**Comment by neutraali** [comment]
Experiencing something similar to this... I can run `react-docgen` fine from the CLI interface, but trying to run it via code (webpack + dev-server) triggers the error. The actual error is:

`TypeError: pluginList.indexOf is not a function at Parser.loadPlugins (index.js:1620)`

As @oliviertassinari described originally, the `pluginList` -parameter is `{ jsx: true, flow: true }` - Which is apparently gotten from `babylon`. Obviously said parameter is an object, not an array, which causes the `indexOf` -check to fail.

I've tried upgrading all my `prop-types` and `babel` -related packages to their latest versions, but that didn't help. `npm list babylon version` reveals that I have `babylon@6.18.0` everywhere else, except `react-docgen` still has it as `babylon@5.8.38`. Could this be the issue?

**Comment by oliviertassinari** [comment]
@danez Material-UI has been relying on the v3.0.0 beta for months now. It's working great.

**Comment by neutraali** [comment]
@danez tried `v3-dev` - But it seems that branch only has the CLI interface available (at least when installing via NPM)? Anyway I moved on to making a CLI workaround since the NodeJS API is going nowhere.

**Comment by danez** [comment]
just install with npm the latest beta
```
npm install react-docgen@next
```

Installing the branch directly won't work, as there are build steps involved when releasing.
