### ISSUE TITLE
Tests fail with recast >= 0.10.41

### ISSUE THREAD

**Issue by danez** [reactjs/react-docgen#49]
With recast >= 0.10.41 two tests are failing:

```
 FAIL  src/handlers/__tests__/componentDocblockHandler-test.js (11.578s)
● componentDocblockHandler › ClassDeclaration › decorators › it uses the component docblock if present
  - Expected: 'Decorator description' toBe: 'Component description'
        at Spec.eval (src/handlers/__tests__/componentDocblockHandler-test.js:124:43)
● componentDocblockHandler › ES6 named exports › Named class declaration export › decorators › it uses the component docblock if present
  - Expected: 'Decorator description' toBe: 'Component description'
```

I opened already an issue with recast benjamn/recast#245, but no response yet. Maybe you guys know why it changed.

**Comment by fkling** [comment]
There have been some changes around how decorators are printed. I guess it may also have impacted comment attachment. Whether that's a bug or intended I don't know.

**Comment by fkling** [comment]
Looks like a bug to me: The `comments` property contains the decorator comment, the `leadingComments` property contains the component comment: http://astexplorer.net/#/lBRfRefMun .

Could probably still fix this from my side.
