### ISSUE TITLE
Descriptions not appearing in the JSON output

### ISSUE THREAD

**Issue by khushal87** [reactjs/react-docgen#505]
I have my component defined, it has comments in the component top as well as in the props. But none of them are rendered as description in the output JSON. How can I solve the issue?

I am calling the parse as `parse(data, null, null, { filename: file })` where data is the file content and file is file name. Can anyone help me if I am missing out anything?

Note: The files are in tsx

Eg:
```
/** This is a switch component */
export type SwitchProps = NativeSwitchProps & {
    /**
     * @default Primary
     * The color of the component.
     */
    color?: string;
};
```

**Comment by cjduncana** [comment]
How did you solve this? @khushal87
