### ISSUE TITLE
BREAK with TypeScript 4.3

### ISSUE THREAD

**Issue by deleonio** [reactjs/react-docgen#508]
![image](https://user-images.githubusercontent.com/6279703/119755786-e1f76b80-bea2-11eb-89cc-1316432271c4.png)

**Comment by denchen** [comment]
I believe the issue is being tracked here:
https://github.com/styleguidist/react-docgen-typescript/issues/356

**Comment by danez** [comment]
Yeah this is not directly related to code in `react-docgen`, but the plugin in `react-docgen-typescript`, as linked above.
