### ISSUE TITLE
TypeScript: "'Const declarations' require an initialization value" when using forwardRef<T, P> and parse

### ISSUE THREAD

**Issue by penx** [reactjs/react-docgen#522]
With the following code:

```tsx
import React from 'react';

const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>((props: CheckboxProps, ref) => <div {...props} />);

type CheckboxProps = React.InputHTMLAttributes<HTMLInputElement>;

export default Checkbox;
```

If I process with the CLI using `npm exec react-docgen ./src/index.tsx` then it passes fine, but if I use `parse` i.e. `const componentInfo = parse(src);`then I get

```
/Users/penx/Development/penx/govuk-react/node_modules/@babel/parser/lib/index.js:810
    const err = new SyntaxError(message);
                ^

SyntaxError: unknown: 'Const declarations' require an initialization value. (3:65)

  1 | import React from 'react';
  2 |
> 3 | const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>((props: CheckboxProps, ref) => <div {...props} />);
    |                                                                  ^
  4 |
  5 | type CheckboxProps = React.InputHTMLAttributes<HTMLInputElement>;
```

Note that this processes fine if I remove the generics from `forwardRef`:

```tsx
import React from 'react';

const Checkbox = React.forwardRef((props: CheckboxProps, ref) => <div {...props} />);

type CheckboxProps = React.InputHTMLAttributes<HTMLInputElement>;

export default Checkbox;
```

I'm using react-docgen 5.4.0.

Do I need to pass additional options when using `parse` for TypeScript, that are done automatically when using the CLI? Or is this perhaps a sub dependency issue?

**Comment by penx** [comment]
In case it helps, this error was one of several docgen issues encountered on this build:

https://github.com/govuk-react/govuk-react/pull/983/checks?check_run_id=3621767697

against this commit:

https://github.com/govuk-react/govuk-react/tree/e27b551ea497afdc3231223b9ed1f1fd19502efe

On this PR:

https://github.com/govuk-react/govuk-react/pull/983

**Comment by danez** [comment]
works in 6.0
