### ISSUE TITLE
Typescript: PropTypes.func is reported as 'custom' type when asserted to a more specific type

### ISSUE THREAD

**Issue by juzerzarif** [reactjs/react-docgen#525]
I have the following prop-types definition in my React component:
```typescript
import PropTypes from 'prop-types';
import type { InferProps, Requireable } from 'prop-types';

const propTypes = {
  someFunc: PropTypes.func as Requireable<(a: string) => boolean>, // The type assertion helps narrow the type in the props interface
};

const MyComponent: React.FC<InferProps<typeof propTypes>> = (props) => {...}
```

react-docgen parses the `someFunc` prop as `{ type: { name: 'custom', raw: 'PropTypes.func as Requireable<(a: string) => boolean>' } }`. While this is technically correct, `func` would be a more accurate type name here.

Is there a way for react-docgen to be able to narrow the type of a  prop like that?

**Comment by danez** [comment]
works in version 6.0
