### ISSUE TITLE
Can I use this to generate ReactJS docs?

### ISSUE THREAD

**Issue by adriaanbalt** [reactjs/react-docgen#54]
Can I use this to generate ReactJS documentation and a standalone HTML page that can be used by users?

**Comment by fkling** [comment]
Yes. `react-docgen` will extract information about React components from your source files and give you a JSON blob, from which you can generate human readable information in any format you like. Have a look at the [example that generates Markdown](https://github.com/reactjs/react-docgen/blob/master/example/generateMarkdown.js).

**Comment by fkling** [comment]
Unless of course you mean generating documentation for React itself, in which case the answer is no.
