### ISSUE TITLE
[Question][Tsx][Class] simplest case is not support yet

### ISSUE THREAD

**Issue by c0ncentus** [reactjs/react-docgen#561]
hi,
![image](https://user-images.githubusercontent.com/25374826/152675272-88f2b989-e227-4881-aa3c-e850d3b7fa9f.png)

When using TSX i delete PropsType because nice to have only in javascript (my opinion).
I want to use the full power of tsx than "an another dependency".

I don't know if it's possible to care of that but I have tons of class of components with the same pattern :

- class Something extends Component<{case1?:string, case2: ICustomInterface }, { }> 
- or class Something extends Component<ClassCompoInterfaceProps, ClassCompoInterfaceState> 

it is simplest case I have and no support yet by the playground https://reactcommunity.org/react-docgen/ .

It will be added ?

**Comment by danez** [comment]
This already works, but you need to currently export a component for it to be detected. So in your case do `export class ...`

I will change the Playground so that exporting is not necessary anymore.
