### ISSUE TITLE
Are there any TypeScript typings for this library?

### ISSUE THREAD

**Issue by matyasf** [reactjs/react-docgen#568]
I'm struggling with typing the output of this library, has someone already done so? The only thing I've found was in the [Readme](https://github.com/reactjs/react-docgen#types), but its very vague , e.g. `"elements": [{ <element-type> }` -- what is here `<element-type>`? Has someone already typed the output? Thanks!

**Comment by IanVS** [comment]
I believe that much of the code has been converted to typescript in the main branch, but has not yet been released.

**Comment by danez** [comment]
There is now version <a href='https://github.com/reactjs/react-docgen/releases/tag/v6.0.0-alpha.1'>v6.0.0-alpha.1</a> which is the first pre-release with typescript typings included.

**Comment by lmiller1990** [comment]
Thanks @danez - I'm trying out alpha.3, I'm noticing the return types for `parse` are not quite correct - they seem to indicate `DocumentationObject`, but in reality I get an object with:

```js
[ { description: '', displayName: 'Counter', methods: [ [Object] ] } ]
```

I'm guessing this will be fixed in a future release - anything I can do to help out?

**Comment by danez** [comment]
This has changed now in 6.0.0-alpha.4 `parse()` now always returns `Documentation[]`.
