### ISSUE TITLE
Error when component is declared before instantiated

### ISSUE THREAD

**Issue by abejfehr** [reactjs/react-docgen#58]
Our components are written in CJSX, which is compiled to CoffeeScript and then straight to JS. When running react-docgen on the resultant files, I receive the `ERROR_MISSING_DEFINITION` error. I realize now that this because somewhere during the conversion process, my JS ends up looking like this:

    var Component, React;

    React = require('react');

    /**
     * The is a component to test the document generation
     */

    Component = React.createClass({
      displayName: 'Component',
      propTypes: {

    ...

Since `Component = React.createClass({` isn't preceded by `var`, this documentation generator refuses to see the definition. This is really annoying.

**Comment by fkling** [comment]
Mmh, I see. I guess the issue is with how we resolve the identifiers to values. I guess we should be able to detect that there is only a single assignment to the variable (in the top level scope) (`React` and `Component`) and use that value then.

**Comment by abejfehr** [comment]
Forgive my potential ignorance, but would I be able to write a custom resolver that would (forgive the pun) resolve this issue?

**Comment by fkling** [comment]
Well, if this is the only exported component, you shouldn't have to write your own resolver, we just need to fix the default one :)

As a workaround, if this is the only React component in the file anyway, you can use the `findAllComponentDefinitions` resolver:

```
react-docgen --resolver findAllComponentDefinitions src/
```
