### ISSUE TITLE
variables for propTypes

### ISSUE THREAD

**Issue by khankuan** [reactjs/react-docgen#65]
Hi, im using `oneOf(myArray)`. The problem is because myArray is a variable and declared above the component.

**Comment by fkling** [comment]
Can you elaborate? What exactly is the problem? Do you get an error? Do you get unexpected output? What is the output your get and what is the output you would want to get?

**Comment by khankuan** [comment]
sample snippet
```
const types = ['dark', 'light'];
...
static propTypes = {
  types: React.PropTypes.oneOf(types)
}

```
This resulted in the value being 'types' as a string. It would be nice if we can replace it with the variable value instead of the variable name.

**Comment by ondrejbartas** [comment]
👍

**Comment by fkling** [comment]
This should be fixed with d3dbb2e0214c8d5e84089c25a970479186e95383 which is included in the v2.12.0 release.

**Comment by leepowellcouk** [comment]
Sorry to raise an old issue, but should this work if the values are kept in an imported file?

```
import { types } from './types';
...
static propTypes = {
  types: React.PropTypes.oneOf(types)
}
```

**Comment by fkling** [comment]
@leepowellcouk: No, react-docgen doesn't resolve dependencies.

**Comment by fchwpo** [comment]
Its not working for oneOfType

**Comment by fchwpo** [comment]
Like in my case 
`const columnProps = [
	PropTypes.bool, //can be a boolean
	PropTypes.number, //can be a number
	PropTypes.string, //can be a string,
	PropTypes.shape({
		size: PropTypes.oneOfType([PropTypes.bool, PropTypes.number, PropTypes.string]), // An object that could be one of many types
		order: stringOrNumber,
		offset: stringOrNumber
	})
];

const propTypes = {
	/**
	 * The number of columns to span on extra small devices (<576px) 
	 * 
	 */
	xs : PropTypes.oneOfType(columnProps),
	/**
	 * The number of columns to span on small devices (≥576px)
	 * 
	 */
	sm : PropTypes.oneOfType(columnProps),
	/**
	 * The number of columns to span on medium devices (≥768px)
	 * 
	 */
	md : PropTypes.oneOfType(columnProps),
	/**
	 * The number of columns to span on large devices (≥992px)
	 * 
	 */
	lg : PropTypes.oneOfType(columnProps),
	/**
	 * The number of columns to span on extra large devices (≥1200px)
	 * 
	 */
	xl : PropTypes.oneOfType(columnProps),
	/**
	 * Custom ClassName String
	 */
	className : PropTypes.string,
	/**
	 * Custom Class Name Object
	 */
	cssModule : PropTypes.object,
	/**
	 * WIP
	 */
	widths : PropTypes.array
}`
