### ISSUE TITLE
Immutable Prop Types

### ISSUE THREAD

**Issue by ondrejbartas** [reactjs/react-docgen#76]
Hi I am using a lot `immutable.js`.

https://www.npmjs.com/package/react-immutable-proptypes

```jsx
import IPT from 'react-immutable-proptypes';
import React, { PropTypes as RPT } from 'react';

export default class Slider extends Component {
  static propTypes = {
    interval:       IPT.contains({
      defaultValue: RPT.number.isRequired,
      max:          RPT.number.isRequired,
      min:          RPT.number.isRequired,
      step:         RPT.number.isRequired
    }).isRequired
  }

  render() {
    return (<div />)
  }
}
```

Would be nice to be able to get similar result as shape is providing

**Comment by fkling** [comment]
I'm not sure it makes sense to integrate this directly into react-docgen, but it shouldn't be too difficult to write your own handler that understands these constructs. Have a look at https://github.com/reactjs/react-docgen/blob/master/src/handlers/propTypeHandler.js as a start. We might need to tweak some APIs to make it easier to generate correct output.
