### ISSUE TITLE
Create example for generating reStructuredText

### ISSUE THREAD

**Issue by woodb** [reactjs/react-docgen#8]
Following up from #7, an example that generates reStructuredText would open up this tool for other documentation generating softwares such as [Sphinx](http://sphinx-doc.org/).

**Comment by fkling** [comment]
Did you make any progress with this?

**Comment by pwexler** [comment]
shameless plug:
You might consider using docutils_react_docgen
https://pypi.python.org/pypi/docutils_react_docgen
new version  0.1.0 coming today or tomorrow with ability to
Infer CommonJS module name if bower.json or package.json is available

**Comment by fkling** [comment]
@pwexler: That's awesome! I created https://github.com/reactjs/react-docgen/wiki/Markup-generators to list and promote tools like yours.

**Comment by woodb** [comment]
Super cool @pwexler! Wish it was on GitHub though :) I'll definitely check this out, I think we can close this issue @fkling in light of @pwexler's project...

**Comment by pwexler** [comment]
thanks for your support.  just released 0.1.0 - with CommonJS module name support.
