### ISSUE TITLE
Fix Typo

### ISSUE THREAD

**Issue by fab1an** [reactjs/react-docgen#84]
https://github.com/reactjs/react-docgen/blob/dca8ec9d57b4833f7ddb3164bedf4d74578eee1e/src/utils/getPropType.js#L61

"unkown" -> "unknown"

**Comment by fkling** [comment]
I think you mean this line: https://github.com/reactjs/react-docgen/blob/dca8ec9d57b4833f7ddb3164bedf4d74578eee1e/src/utils/getPropType.js#L71 :) Good catch! Feel free to make a PR if you want.

**Comment by fab1an** [comment]
#86
