### ISSUE TITLE
Imported propTypes of dependencies

### ISSUE THREAD

**Issue by fab1an** [reactjs/react-docgen#87]
I often nest my proptypes like this:

```javascript 
class Parent extends React.Component {
    static propTypes = {
        something: pt.string.isRequired,
        child: pt.shape(Child.propTypes).isRequired
    }
}
```

`react-docgen` gives me
```json
"type": {
    "name": "shape",
    "value": "unkown"
},
```

for the parameter. Can I somehow make it give me `Child`? I tried using `instanceOf()` but that didn't work either.

**Comment by fkling** [comment]
Yeah, at the very least it should give you access to the string representation of the value, i.e. `Child.propTpyes`.

**Comment by fkling** [comment]
Now you will be getting 

```js
"type": {
  "name": "shape",
  "value": "Child.propTypes",
  "computed": true
}
```

which is more in line with how the other types work. We may change the structure in the future, but that's still a bit out (if we do it at all).

I don't know yet when I'm going to release the next version.
