### ISSUE TITLE
react-docgen v6.0.0 & older changelogs

### ISSUE THREAD

**Issue by apurv-1** [reactjs/react-docgen#874]
Hi, I am working on an older package upgrade because it uses react-docgen v2.4.0 as a dependency. I am looking for the changelog but couldn't find it.

This [CHANGE.LOG](https://github.com/reactjs/react-docgen/blob/main/packages/react-docgen/CHANGELOG.md) only has version history from v6.0.0 and above. Anyone knows where i can find it?

**Comment by danez** [comment]
You can find all changelogs here: https://github.com/reactjs/react-docgen/releases

**Comment by apurv-1** [comment]
Got it, Thanks!
