### ISSUE TITLE
Support for IE11?

### ISSUE THREAD

**Issue by vizath** [reactjs/react-docgen#88]
Hi,
2.8 added to references to `Array.find`, which is not supported by IE11.

Is this package intended to work in browsers, including IE11 ?
Looks like Edge supports it though.
http://kangax.github.io/compat-table/es6/#test-Array.prototype_methods

You can go in to http://www.material-ui.com/#/components/dropdown-menu with IE11 to get the error.

Thanks.

**Comment by fkling** [comment]
Does that site even use `react-docgen`? `react-docgen` is a command line tool. If someone runs it in the browser, they have to make sure the environment is compatible. `find` is easily to polyfill.

**Comment by vizath** [comment]
It is probably related to https://github.com/reactjs/react-docgen/pull/39 (oliviertassinari works on MUI), where there is no mention that `react-docgen` shouldn't work on browser.

They do use it this way:
https://github.com/callemall/material-ui/blob/78beb5455d2fa37894d507b301ba161c46a10ab0/docs/src/app/components/CodeExample/index.js#L2
where `this.props.code` would come from https://github.com/callemall/material-ui/blob/78beb5455d2fa37894d507b301ba161c46a10ab0/docs/src/app/components/pages/components/AppBar/Page.js#L10

I'll open a PR in MUI to add this polyfill tomorrow then.

**Comment by fkling** [comment]
Oh ok. Yeah, there is nothing that should prevent react-docgen from running in the browser, but it's not specifically designed for that. In other words, we are not going to *not* use any features only because browsers do not support it.
