### ISSUE TITLE
HTML generation

### ISSUE THREAD

**Issue by mvolkmann** [reactjs/react-docgen#92]
Has anyone taken the next step and created a tool that converts the output from this tool into HTML?

**Comment by fkling** [comment]
https://github.com/reactjs/react-docgen/tree/master/example shows an example how one could generate markdown (and therefore HTML) from the JSON. There are also [site generators that use react-docgen](https://github.com/reactjs/react-docgen/wiki#site-generators).

**Comment by jackyon** [comment]
@fkling,
I have tried the example cli "react-docgen components/* | buildDocs.sh",
it reminds me "-bash: buildDocs.sh: command not found"

if I copied that two files to my project folder, it works, but looks like the REAME.md create the wrong format of markdown, it still json file:

`{
  "app/components/Header/index.js": {
    "description": "General component description.",
    "methods": []
  }
}`

plz advise.
