### ISSUE TITLE
Generating JSON for single component gives JSON incompatible with buildDocs.sh

### ISSUE THREAD

**Issue by i-a-n** [reactjs/react-docgen#94]
When using react-docgen to generate JSON for just a _single_ component, like so (using the provided example directory):

```
$ react-docgen components/Component.js
{
    "description": "General component description.",
    "displayName": "Component",
    "methods": [],
    "props": {
        "bar": {
            "type": {
                "name": "number"
            },
            "required": false,
            "description": "Prop description",
            "defaultValue": {
                "value": "21",
                "computed": false
            }
        }
    },
    "composes": ["Foo"]
}
```

The JSON output's structure differs from when using react-docgen to generate JSON for _multiple_ components. Like so:

```
$ react-docgen components/*
{
    "components/Component.js": {
        "description": "General component description.",
        "displayName": "Component",
        "methods": [],
        "props": {
            "bar": {
                "type": {
                    "name": "number"
                },
                "required": false,
                "description": "Prop description",
                "defaultValue": {
                    "value": "21",
                    "computed": false
                }
            }
        },
        "composes": ["Foo"]
    },
    "components/Component2.js": {
        "description": "General component description.",
        "displayName": "Component2",
        "methods": [],
        "props": {
            "bar": {
                "type": {
                    "name": "number"
                },
                "required": false,
                "description": "Prop description",
                "defaultValue": {
                    "value": "21",
                    "computed": false
                }
            }
        },
        "composes": ["Foo"]
    }
}
```

As you can see, the first level of the single-component object (`object[0]`) equals "description", whereas the first level of the multiple-component object equals an iterable object (which is expected). For this reason, `buildDocs.sh` fails on the single-component object because it can't iterate over a non-object:

```
$ react-docgen components/Component.js | ./buildDocs.sh
~/dev/union/react-docgen/example/generateMarkdown.js:65
    Object.keys(props).sort().map(function(propName) {
           ^

TypeError: Cannot convert undefined or null to object
```

I think it'd be helpful if react-docgen handled single-component generation by outputting the same JSON structure as with multiple-components. Let me know if you need more info, or if I totally misunderstood something!

**Comment by fkling** [comment]
Mmh... I understand, but I'd argue that it's very uncommon that only a single file is passed to react-docgen. That's a deliberate decision, so I would assume the user only wants to get the docs for that specific component. Also note that `./buildDocs.sh` is really just an example, not necessarily something you should use in production as it is.

If a directory is passed or multiple files are passed, you will always get the second output, even if only one component is found.

Does that make sense?

**Comment by i-a-n** [comment]
Yep, makes sense, thanks for the reply!

I personally don't think it's great software design to do that (my real-world problem has to do with regenerating documentation _only_ for components being updated, which is sometimes just one component, breaking my doc builder), but obviously there are many ways around it and maybe my usage pattern wasn't great to start off with.

Thanks again!

**Comment by fkling** [comment]
I see... I'm usually not a fan of something like this either.
